// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/validate/pb/validate.proto

package fs_base_validate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	VerId                string    `protobuf:"bytes,2,opt,name=verId,proto3" json:"verId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5fd6021931f40c, []int{0}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *CreateResponse) GetVerId() string {
	if m != nil {
		return m.VerId
	}
	return ""
}

type CreateRequest struct {
	UserId               string             `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Do                   int64              `protobuf:"varint,2,opt,name=do,proto3" json:"do,omitempty"`
	Mode                 int64              `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	To                   string             `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	OnVerification       *pb.OnVerification `protobuf:"bytes,5,opt,name=onVerification,proto3" json:"onVerification,omitempty"`
	Metadata             *pb.Metadata       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5fd6021931f40c, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateRequest) GetDo() int64 {
	if m != nil {
		return m.Do
	}
	return 0
}

func (m *CreateRequest) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *CreateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CreateRequest) GetOnVerification() *pb.OnVerification {
	if m != nil {
		return m.OnVerification
	}
	return nil
}

func (m *CreateRequest) GetMetadata() *pb.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type VerificationRequest struct {
	VerId                string             `protobuf:"bytes,1,opt,name=verId,proto3" json:"verId,omitempty"`
	Code                 string             `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Do                   int64              `protobuf:"varint,3,opt,name=do,proto3" json:"do,omitempty"`
	OnVerification       *pb.OnVerification `protobuf:"bytes,4,opt,name=onVerification,proto3" json:"onVerification,omitempty"`
	Metadata             *pb.Metadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VerificationRequest) Reset()         { *m = VerificationRequest{} }
func (m *VerificationRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationRequest) ProtoMessage()    {}
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5fd6021931f40c, []int{2}
}

func (m *VerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationRequest.Unmarshal(m, b)
}
func (m *VerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationRequest.Marshal(b, m, deterministic)
}
func (m *VerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationRequest.Merge(m, src)
}
func (m *VerificationRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationRequest.Size(m)
}
func (m *VerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationRequest proto.InternalMessageInfo

func (m *VerificationRequest) GetVerId() string {
	if m != nil {
		return m.VerId
	}
	return ""
}

func (m *VerificationRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VerificationRequest) GetDo() int64 {
	if m != nil {
		return m.Do
	}
	return 0
}

func (m *VerificationRequest) GetOnVerification() *pb.OnVerification {
	if m != nil {
		return m.OnVerification
	}
	return nil
}

func (m *VerificationRequest) GetMetadata() *pb.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateResponse)(nil), "fs.base.validate.CreateResponse")
	proto.RegisterType((*CreateRequest)(nil), "fs.base.validate.CreateRequest")
	proto.RegisterType((*VerificationRequest)(nil), "fs.base.validate.VerificationRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValidateClient is the client API for Validate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidateClient interface {
	// 验证
	Verification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 创建验证码(自动发送验证码)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type validateClient struct {
	cc *grpc.ClientConn
}

func NewValidateClient(cc *grpc.ClientConn) ValidateClient {
	return &validateClient{cc}
}

func (c *validateClient) Verification(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.validate.Validate/Verification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validateClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/fs.base.validate.Validate/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateServer is the server API for Validate service.
type ValidateServer interface {
	// 验证
	Verification(context.Context, *VerificationRequest) (*pb.Response, error)
	// 创建验证码(自动发送验证码)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterValidateServer(s *grpc.Server, srv ValidateServer) {
	s.RegisterService(&_Validate_serviceDesc, srv)
}

func _Validate_Verification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServer).Verification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.validate.Validate/Verification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServer).Verification(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validate_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.validate.Validate/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Validate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.validate.Validate",
	HandlerType: (*ValidateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verification",
			Handler:    _Validate_Verification_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Validate_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/validate/pb/validate.proto",
}

func init() { proto.RegisterFile("base/validate/pb/validate.proto", fileDescriptor_6d5fd6021931f40c) }

var fileDescriptor_6d5fd6021931f40c = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xd1, 0x4a, 0xeb, 0x40,
	0x10, 0x86, 0xd9, 0xb4, 0x09, 0x3d, 0x73, 0xce, 0x09, 0xba, 0x8a, 0x86, 0xdc, 0xb4, 0x14, 0x85,
	0x82, 0x98, 0x68, 0x7d, 0x00, 0x2f, 0xbc, 0x51, 0x54, 0x84, 0x08, 0xbd, 0xdf, 0x34, 0x53, 0x09,
	0xb5, 0xd9, 0xb8, 0xbb, 0x2d, 0xe8, 0xdb, 0xf8, 0x24, 0x3e, 0x80, 0x2f, 0x25, 0xd9, 0x4d, 0x57,
	0xd3, 0x2a, 0x05, 0xaf, 0xba, 0x3b, 0xf3, 0xff, 0x7f, 0xe7, 0xcb, 0x0e, 0x74, 0x53, 0x26, 0x31,
	0x5e, 0xb0, 0xc7, 0x3c, 0x63, 0x0a, 0xe3, 0x32, 0xb5, 0xe7, 0xa8, 0x14, 0x5c, 0x71, 0xba, 0x35,
	0x91, 0x51, 0xa5, 0x89, 0x96, 0xf5, 0xf0, 0xe8, 0x45, 0x4e, 0x4b, 0x26, 0xa6, 0x28, 0xa2, 0x31,
	0x9f, 0xc5, 0x13, 0x3e, 0x2f, 0x32, 0xa6, 0x72, 0x5e, 0xc4, 0x3a, 0xab, 0x4c, 0xf5, 0xaf, 0xb1,
	0x87, 0x27, 0x1b, 0xc5, 0x52, 0x09, 0xa6, 0xf0, 0xe1, 0xf9, 0xd4, 0x38, 0xfa, 0x37, 0xe0, 0x5f,
	0x08, 0x64, 0x0a, 0x13, 0x94, 0x25, 0x2f, 0x24, 0xd2, 0x03, 0x70, 0xa5, 0x62, 0x0a, 0x03, 0xd2,
	0x23, 0x83, 0xbf, 0x43, 0x3f, 0x5a, 0x8e, 0x74, 0x5f, 0x55, 0x13, 0xd3, 0xa4, 0xbb, 0xe0, 0x2e,
	0x50, 0x5c, 0x65, 0x81, 0xd3, 0x23, 0x83, 0x3f, 0x89, 0xb9, 0xf4, 0xdf, 0x09, 0xfc, 0x5f, 0xc6,
	0x3d, 0xcd, 0x51, 0x2a, 0xba, 0x07, 0xde, 0x5c, 0x6a, 0x21, 0xd1, 0xc2, 0xfa, 0x46, 0x7d, 0x70,
	0x32, 0xae, 0xcd, 0xad, 0xc4, 0xc9, 0x38, 0xa5, 0xd0, 0x9e, 0xf1, 0x0c, 0x83, 0x96, 0xae, 0xe8,
	0x73, 0xa5, 0x51, 0x3c, 0x68, 0x6b, 0x9f, 0xa3, 0x38, 0x3d, 0x07, 0x9f, 0x17, 0x23, 0x14, 0xf9,
	0x24, 0x1f, 0x6b, 0xaa, 0xc0, 0xd5, 0x23, 0xee, 0xdb, 0x11, 0xef, 0x1a, 0xed, 0x64, 0x45, 0x4e,
	0x8f, 0xa1, 0x33, 0x43, 0xc5, 0x32, 0xa6, 0x58, 0xe0, 0x69, 0xeb, 0xb6, 0xb5, 0xde, 0xd6, 0x8d,
	0xc4, 0x4a, 0xfa, 0x6f, 0x04, 0x76, 0x1a, 0x79, 0x35, 0x93, 0x65, 0x27, 0x5f, 0xd8, 0x2b, 0x82,
	0x71, 0x45, 0x60, 0x3e, 0x88, 0x3e, 0xd7, 0x94, 0x2d, 0x4b, 0xb9, 0x4e, 0xd0, 0xfe, 0x3d, 0x81,
	0xbb, 0x91, 0x60, 0xf8, 0x4a, 0xa0, 0x33, 0xaa, 0x37, 0x89, 0x5e, 0xc2, 0xbf, 0x46, 0xd6, 0x61,
	0xb4, 0xba, 0x6c, 0xd1, 0x37, 0xb4, 0xe1, 0xe7, 0x1f, 0xd8, 0x15, 0xb9, 0x06, 0xcf, 0xbc, 0x32,
	0xed, 0xae, 0x67, 0x34, 0xde, 0x3f, 0xec, 0xfd, 0x2c, 0x30, 0x61, 0xa9, 0xa7, 0x17, 0xf1, 0xec,
	0x23, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xc4, 0x64, 0xbb, 0x1c, 0x03, 0x00, 0x00,
}
