// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/validate/pb/validate.proto

package fs_base_validate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValidateClient is the client API for Validate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValidateClient interface {
}

type validateClient struct {
	cc *grpc.ClientConn
}

func NewValidateClient(cc *grpc.ClientConn) ValidateClient {
	return &validateClient{cc}
}

// ValidateServer is the server API for Validate service.
type ValidateServer interface {
}

func RegisterValidateServer(s *grpc.Server, srv ValidateServer) {
	s.RegisterService(&_Validate_serviceDesc, srv)
}

var _Validate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.validate.Validate",
	HandlerType: (*ValidateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base/validate/pb/validate.proto",
}

func init() { proto.RegisterFile("base/validate/pb/validate.proto", fileDescriptor_6d5fd6021931f40c) }

var fileDescriptor_6d5fd6021931f40c = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x2f, 0x48, 0x82, 0xb3, 0xf5, 0x0a,
	0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04, 0xd2, 0x8a, 0xf5, 0x40, 0x6a, 0xf4, 0x60, 0xe2, 0x46, 0x5c,
	0x5c, 0x1c, 0x61, 0x50, 0x76, 0x12, 0x1b, 0x58, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0x24, 0xf0, 0x23, 0x47, 0x00, 0x00, 0x00,
}
