// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/function/pb/function.proto

package fs_base_function

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type GetResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Func                 string    `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	Verification         string    `protobuf:"bytes,3,opt,name=verification,proto3" json:"verification,omitempty"`
	Zh                   string    `protobuf:"bytes,4,opt,name=zh,proto3" json:"zh,omitempty"`
	En                   string    `protobuf:"bytes,5,opt,name=en,proto3" json:"en,omitempty"`
	Api                  string    `protobuf:"bytes,6,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetResponse) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *GetResponse) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

func (m *GetResponse) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *GetResponse) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *GetResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type AddRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Zh                   string   `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"`
	En                   string   `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Verification         string   `protobuf:"bytes,4,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{2}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *AddRequest) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *AddRequest) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *AddRequest) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

type AddResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Func                 string    `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{3}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AddResponse) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type RemoveRequest struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{4}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type UpdateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Zh                   string   `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"`
	En                   string   `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *UpdateRequest) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "fs.base.function.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "fs.base.function.GetResponse")
	proto.RegisterType((*AddRequest)(nil), "fs.base.function.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "fs.base.function.AddResponse")
	proto.RegisterType((*RemoveRequest)(nil), "fs.base.function.RemoveRequest")
	proto.RegisterType((*UpdateRequest)(nil), "fs.base.function.UpdateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FunctionClient is the client API for Function service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionClient interface {
	// 添加功能(用作身份验证/统计运维等)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// 移除功能
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 更新
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// admin or gRPC
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type functionClient struct {
	cc *grpc.ClientConn
}

func NewFunctionClient(cc *grpc.ClientConn) FunctionClient {
	return &functionClient{cc}
}

func (c *functionClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/fs.base.function.Function/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.function.Function/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.function.Function/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/fs.base.function.Function/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServer is the server API for Function service.
type FunctionServer interface {
	// 添加功能(用作身份验证/统计运维等)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// 移除功能
	Remove(context.Context, *RemoveRequest) (*pb.Response, error)
	// 更新
	Update(context.Context, *UpdateRequest) (*pb.Response, error)
	// admin or gRPC
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterFunctionServer(s *grpc.Server, srv FunctionServer) {
	s.RegisterService(&_Function_serviceDesc, srv)
}

func _Function_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.function.Function/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Function_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.function.Function/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Function_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.function.Function/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Function_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.function.Function/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Function_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.function.Function",
	HandlerType: (*FunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Function_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Function_Remove_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Function_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Function_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/function/pb/function.proto",
}

func init() { proto.RegisterFile("base/function/pb/function.proto", fileDescriptor_ca288e03ead2bc39) }

var fileDescriptor_ca288e03ead2bc39 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0x5b, 0x20, 0xdf, 0x37, 0x08, 0xc1, 0x3d, 0x35, 0x44, 0x03, 0xa9, 0x1e, 0x4c, 0x4c,
	0x96, 0x04, 0xaf, 0x5e, 0xe0, 0x20, 0xf7, 0x1a, 0x7f, 0x40, 0x4b, 0xa7, 0xa1, 0x21, 0xec, 0xae,
	0xdd, 0x85, 0x03, 0x3f, 0xc2, 0x7f, 0xe0, 0x7f, 0x35, 0x3b, 0x2d, 0x05, 0x4a, 0xf5, 0xa0, 0xa7,
	0xce, 0xce, 0x9b, 0x79, 0x7d, 0x6f, 0xf2, 0x60, 0x14, 0x47, 0x1a, 0x27, 0xe9, 0x56, 0x2c, 0x4d,
	0x26, 0xc5, 0x44, 0xc5, 0x55, 0xcd, 0x55, 0x2e, 0x8d, 0x64, 0x83, 0x54, 0x73, 0x3b, 0xc3, 0x0f,
	0xfd, 0xe1, 0xe3, 0x5e, 0xaf, 0x55, 0x94, 0xaf, 0x31, 0xe7, 0x4b, 0xb9, 0x99, 0xa4, 0x72, 0x2b,
	0x92, 0x88, 0xb6, 0x89, 0x4b, 0xc5, 0xf4, 0x2d, 0xd6, 0x83, 0x31, 0xc0, 0x02, 0x4d, 0x88, 0xef,
	0x5b, 0xd4, 0x86, 0x31, 0x68, 0x59, 0x1a, 0xdf, 0x19, 0x3b, 0x0f, 0xff, 0x43, 0xaa, 0x83, 0x4f,
	0x07, 0xba, 0x34, 0xa2, 0x95, 0x14, 0x1a, 0xd9, 0x3d, 0xb4, 0xb5, 0x89, 0x0c, 0xd2, 0x50, 0x77,
	0xda, 0xe7, 0x07, 0x01, 0xaf, 0xb6, 0x1b, 0x16, 0x60, 0xc5, 0xe4, 0x1e, 0x99, 0x58, 0x00, 0x57,
	0x3b, 0xcc, 0xb3, 0x34, 0x5b, 0x92, 0x1c, 0xdf, 0x23, 0xec, 0xac, 0xc7, 0xfa, 0xe0, 0xee, 0x57,
	0x7e, 0x8b, 0x10, 0x77, 0xbf, 0xb2, 0x6f, 0x14, 0x7e, 0xbb, 0x78, 0xa3, 0x60, 0x03, 0xf0, 0x22,
	0x95, 0xf9, 0x1d, 0x6a, 0xd8, 0x32, 0x88, 0x01, 0x66, 0x49, 0x72, 0x70, 0x50, 0xe2, 0x4e, 0x85,
	0x97, 0x8c, 0x6e, 0x8d, 0xd1, 0xab, 0x18, 0xeb, 0xaa, 0x5a, 0x97, 0xaa, 0x82, 0x05, 0x74, 0xe9,
	0x1f, 0x7f, 0x3d, 0x41, 0x70, 0x07, 0xbd, 0x10, 0x37, 0x72, 0x87, 0x3f, 0x5d, 0x7c, 0x06, 0xbd,
	0x37, 0x95, 0x58, 0xa6, 0xdf, 0x9a, 0x9a, 0x7e, 0xb8, 0xf0, 0xef, 0xa5, 0x0c, 0x04, 0x9b, 0x83,
	0x37, 0x4b, 0x12, 0x76, 0xc3, 0xeb, 0x51, 0xe1, 0xc7, 0xc3, 0x0d, 0x6f, 0xbf, 0x41, 0x4b, 0xcb,
	0xcf, 0xd0, 0x29, 0x84, 0xb3, 0xd1, 0xe5, 0xe0, 0x99, 0xa5, 0xe1, 0x75, 0x35, 0x70, 0xba, 0x5d,
	0x38, 0x6a, 0xda, 0x3e, 0xf3, 0xda, 0xb4, 0x3d, 0x07, 0x6f, 0x81, 0xa6, 0x49, 0xff, 0x31, 0xba,
	0x4d, 0xfa, 0x4f, 0x52, 0x1b, 0x77, 0x28, 0xee, 0x4f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x96,
	0x26, 0x2d, 0x5b, 0x50, 0x03, 0x00, 0x00,
}
