// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/function/pb/function.proto

package fs_base_function

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Func                 string   `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	ProjectId            string   `protobuf:"bytes,3,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetRequest) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *GetRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type GetResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Func                 *Func     `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetResponse) GetFunc() *Func {
	if m != nil {
		return m.Func
	}
	return nil
}

type Func struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Zh                   string   `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"`
	En                   string   `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Api                  string   `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`
	Fcv                  int64    `protobuf:"varint,5,opt,name=fcv,proto3" json:"fcv,omitempty"`
	Level                int64    `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Type                 int64    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{2}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *Func) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *Func) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Func) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Func) GetFcv() int64 {
	if m != nil {
		return m.Fcv
	}
	return 0
}

func (m *Func) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Func) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type UpsertResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Func                 string    `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpsertResponse) Reset()         { *m = UpsertResponse{} }
func (m *UpsertResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertResponse) ProtoMessage()    {}
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{3}
}

func (m *UpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertResponse.Unmarshal(m, b)
}
func (m *UpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertResponse.Marshal(b, m, deterministic)
}
func (m *UpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertResponse.Merge(m, src)
}
func (m *UpsertResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertResponse.Size(m)
}
func (m *UpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertResponse proto.InternalMessageInfo

func (m *UpsertResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *UpsertResponse) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type RemoveRequest struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{4}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type UpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Zh                   string   `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"`
	En                   string   `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Fcv                  int64    `protobuf:"varint,4,opt,name=fcv,proto3" json:"fcv,omitempty"`
	Level                int64    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRequest) Reset()         { *m = UpsertRequest{} }
func (m *UpsertRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest) ProtoMessage()    {}
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca288e03ead2bc39, []int{5}
}

func (m *UpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest.Unmarshal(m, b)
}
func (m *UpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest.Merge(m, src)
}
func (m *UpsertRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest.Size(m)
}
func (m *UpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest proto.InternalMessageInfo

func (m *UpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpsertRequest) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *UpsertRequest) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *UpsertRequest) GetFcv() int64 {
	if m != nil {
		return m.Fcv
	}
	return 0
}

func (m *UpsertRequest) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "fs.base.function.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "fs.base.function.GetResponse")
	proto.RegisterType((*Func)(nil), "fs.base.function.Func")
	proto.RegisterType((*UpsertResponse)(nil), "fs.base.function.UpsertResponse")
	proto.RegisterType((*RemoveRequest)(nil), "fs.base.function.RemoveRequest")
	proto.RegisterType((*UpsertRequest)(nil), "fs.base.function.UpsertRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FunctionClient is the client API for Function service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionClient interface {
	// admin or gRPC
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type functionClient struct {
	cc *grpc.ClientConn
}

func NewFunctionClient(cc *grpc.ClientConn) FunctionClient {
	return &functionClient{cc}
}

func (c *functionClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/fs.base.function.Function/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServer is the server API for Function service.
type FunctionServer interface {
	// admin or gRPC
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterFunctionServer(s *grpc.Server, srv FunctionServer) {
	s.RegisterService(&_Function_serviceDesc, srv)
}

func _Function_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.function.Function/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Function_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.function.Function",
	HandlerType: (*FunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Function_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/function/pb/function.proto",
}

func init() { proto.RegisterFile("base/function/pb/function.proto", fileDescriptor_ca288e03ead2bc39) }

var fileDescriptor_ca288e03ead2bc39 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdf, 0x4b, 0x02, 0x41,
	0x10, 0xe6, 0x7e, 0x59, 0x8e, 0x28, 0xb2, 0x44, 0x1c, 0x62, 0x24, 0x5b, 0x0f, 0x52, 0xb0, 0x82,
	0xfd, 0x07, 0x3d, 0x28, 0xf5, 0x10, 0x71, 0xd1, 0x73, 0xdc, 0x9d, 0x73, 0x68, 0xea, 0xee, 0x76,
	0xbb, 0x27, 0xe4, 0x5f, 0xd0, 0x9f, 0x1d, 0xbb, 0xe7, 0xa9, 0x94, 0x42, 0x3d, 0xdd, 0x37, 0xdf,
	0xdc, 0xce, 0x7c, 0xdf, 0xcc, 0xc0, 0x65, 0x12, 0x2b, 0x1c, 0x64, 0x05, 0x4f, 0xf5, 0x4c, 0xf0,
	0x81, 0x4c, 0xb6, 0x98, 0xc9, 0x5c, 0x68, 0x41, 0xda, 0x99, 0x62, 0xe6, 0x1f, 0x56, 0xf1, 0x9d,
	0xdb, 0xb5, 0x9a, 0xcb, 0x38, 0x9f, 0x63, 0xce, 0x52, 0xb1, 0x1c, 0x64, 0xa2, 0xe0, 0x93, 0xd8,
	0xbe, 0xb6, 0xb5, 0x64, 0x62, 0xbf, 0xe5, 0x73, 0xfa, 0x0c, 0x30, 0x46, 0x1d, 0xe1, 0x47, 0x81,
	0x4a, 0x93, 0x36, 0x78, 0xb1, 0x9c, 0x85, 0x4e, 0xcf, 0xe9, 0xd7, 0x23, 0x03, 0x09, 0x01, 0xdf,
	0x14, 0x0e, 0x5d, 0x4b, 0x59, 0x4c, 0xba, 0x50, 0x97, 0xb9, 0x78, 0xc7, 0x54, 0x3f, 0x4c, 0x42,
	0xcf, 0x26, 0x76, 0x04, 0x7d, 0x83, 0x86, 0xad, 0xa8, 0xa4, 0xe0, 0x0a, 0xc9, 0x35, 0x04, 0x4a,
	0xc7, 0x1a, 0x6d, 0xd1, 0xc6, 0xb0, 0xc5, 0x2a, 0xbd, 0x2f, 0x86, 0x8d, 0xca, 0x24, 0xb9, 0xd9,
	0x6b, 0xd3, 0x18, 0x9e, 0xb3, 0x9f, 0xa6, 0xd8, 0xa8, 0xe0, 0x69, 0xd9, 0x9e, 0x7e, 0x39, 0xe0,
	0x9b, 0x70, 0xab, 0xcd, 0xd9, 0xd3, 0xd6, 0x02, 0x77, 0x3d, 0xdd, 0xa8, 0x75, 0xd7, 0x53, 0x13,
	0x23, 0xdf, 0x88, 0x74, 0x91, 0x57, 0x0e, 0xfd, 0x9d, 0xc3, 0x36, 0x78, 0x59, 0xba, 0x0a, 0x83,
	0x9e, 0xd3, 0xf7, 0x22, 0x03, 0xc9, 0x19, 0x04, 0x0b, 0x5c, 0xe1, 0x22, 0xac, 0x59, 0xae, 0x0c,
	0x4c, 0x37, 0xfd, 0x29, 0x31, 0x3c, 0xb1, 0xa4, 0xc5, 0xf4, 0x11, 0x5a, 0xaf, 0x52, 0x61, 0xfe,
	0x5f, 0xbb, 0x07, 0xa6, 0x4a, 0xaf, 0xa0, 0x19, 0xe1, 0x52, 0xac, 0xb0, 0x5a, 0xc6, 0x01, 0x7b,
	0x74, 0x06, 0xcd, 0xaa, 0xe1, 0xb1, 0x8d, 0xfd, 0x61, 0x02, 0xc6, 0xaf, 0x7f, 0xc0, 0x6f, 0xb0,
	0xe7, 0x77, 0xf8, 0x04, 0xa7, 0xa3, 0xcd, 0xf4, 0xc9, 0x3d, 0x78, 0x63, 0xd4, 0xa4, 0xfb, 0x7b,
	0x2f, 0xbb, 0xe3, 0xe9, 0x5c, 0x1c, 0xc9, 0x96, 0x93, 0x49, 0x6a, 0xf6, 0xe0, 0xee, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0x84, 0xb2, 0x64, 0xd2, 0x02, 0x00, 0x00,
}
