// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/sms/pb/sms.proto

package fs_base_sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SMSClient is the client API for SMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SMSClient interface {
}

type sMSClient struct {
	cc *grpc.ClientConn
}

func NewSMSClient(cc *grpc.ClientConn) SMSClient {
	return &sMSClient{cc}
}

// SMSServer is the server API for SMS service.
type SMSServer interface {
}

func RegisterSMSServer(s *grpc.Server, srv SMSServer) {
	s.RegisterService(&_SMS_serviceDesc, srv)
}

var _SMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.sms.SMS",
	HandlerType: (*SMSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base/sms/pb/sms.proto",
}

func init() { proto.RegisterFile("base/sms/pb/sms.proto", fileDescriptor_7a134f7cae7690a4) }

var fileDescriptor_7a134f7cae7690a4 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2f, 0xce, 0x2d, 0xd6, 0x2f, 0x48, 0x02, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xdc, 0x69, 0xc5, 0x7a, 0x20, 0x19, 0xbd, 0xe2, 0xdc, 0x62, 0x23, 0x56, 0x2e, 0xe6, 0x60, 0xdf,
	0xe0, 0x24, 0x36, 0xb0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xae, 0x8b, 0x58, 0xf3, 0x33,
	0x00, 0x00, 0x00,
}
