// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safety/unblock/pb/unblock.proto

package fs_safety_unblock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnblockClient is the client API for Unblock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnblockClient interface {
}

type unblockClient struct {
	cc *grpc.ClientConn
}

func NewUnblockClient(cc *grpc.ClientConn) UnblockClient {
	return &unblockClient{cc}
}

// UnblockServer is the server API for Unblock service.
type UnblockServer interface {
}

func RegisterUnblockServer(s *grpc.Server, srv UnblockServer) {
	s.RegisterService(&_Unblock_serviceDesc, srv)
}

var _Unblock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.safety.unblock.Unblock",
	HandlerType: (*UnblockServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "safety/unblock/pb/unblock.proto",
}

func init() { proto.RegisterFile("safety/unblock/pb/unblock.proto", fileDescriptor_d169fad80b63771e) }

var fileDescriptor_d169fad80b63771e = []byte{
	// 72 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x4e, 0x4c, 0x4b,
	0x2d, 0xa9, 0xd4, 0x2f, 0xcd, 0x4b, 0xca, 0xc9, 0x4f, 0xce, 0xd6, 0x2f, 0x48, 0x82, 0x31, 0xf5,
	0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04, 0xd3, 0x8a, 0xf5, 0x20, 0x6a, 0xf4, 0xa0, 0x12, 0x46,
	0x9c, 0x5c, 0xec, 0xa1, 0x10, 0x66, 0x12, 0x1b, 0x58, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0xd8, 0xb1, 0x58, 0x47, 0x00, 0x00, 0x00,
}
