// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/user/pb/user.proto

package fs_base_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

// UserServer is the server API for User service.
type UserServer interface {
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.user.User",
	HandlerType: (*UserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base/user/pb/user.proto",
}

func init() { proto.RegisterFile("base/user/pb/user.proto", fileDescriptor_c941ea4089a6591e) }

var fileDescriptor_c941ea4089a6591e = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0x48, 0x02, 0xd3, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0x3c, 0x69, 0xc5, 0x7a, 0x20, 0x39, 0x3d, 0x90, 0x98, 0x11, 0x1b, 0x17, 0x4b, 0x68, 0x71,
	0x6a, 0x51, 0x12, 0x1b, 0x58, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x86, 0xf0, 0xbe,
	0x37, 0x00, 0x00, 0x00,
}
