// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/user/pb/user.proto

package fs_base_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c941ea4089a6591e, []int{0}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FindRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c941ea4089a6591e, []int{1}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FindResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	UserId               string    `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Level                int64     `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Phone                string    `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Enterprise           string    `protobuf:"bytes,5,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
	Email                string    `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	FromProjectId        string    `protobuf:"bytes,7,opt,name=fromProjectId,proto3" json:"fromProjectId,omitempty"`
	FromAppId            string    `protobuf:"bytes,8,opt,name=fromAppId,proto3" json:"fromAppId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c941ea4089a6591e, []int{2}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *FindResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FindResponse) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FindResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *FindResponse) GetEnterprise() string {
	if m != nil {
		return m.Enterprise
	}
	return ""
}

func (m *FindResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FindResponse) GetFromProjectId() string {
	if m != nil {
		return m.FromProjectId
	}
	return ""
}

func (m *FindResponse) GetFromAppId() string {
	if m != nil {
		return m.FromAppId
	}
	return ""
}

type AddRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Enterprise           string   `protobuf:"bytes,2,opt,name=enterprise,proto3" json:"enterprise,omitempty"`
	Level                int64    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	FromProjectId        string   `protobuf:"bytes,6,opt,name=fromProjectId,proto3" json:"fromProjectId,omitempty"`
	FromAppId            string   `protobuf:"bytes,7,opt,name=fromAppId,proto3" json:"fromAppId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c941ea4089a6591e, []int{3}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddRequest) GetEnterprise() string {
	if m != nil {
		return m.Enterprise
	}
	return ""
}

func (m *AddRequest) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *AddRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddRequest) GetFromProjectId() string {
	if m != nil {
		return m.FromProjectId
	}
	return ""
}

func (m *AddRequest) GetFromAppId() string {
	if m != nil {
		return m.FromAppId
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "fs.base.user.UpdateRequest")
	proto.RegisterType((*FindRequest)(nil), "fs.base.user.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "fs.base.user.FindResponse")
	proto.RegisterType((*AddRequest)(nil), "fs.base.user.AddRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*pb.Response, error)
	FindByUserId(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindByEmail(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindByPhone(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindByEnterprise(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	UpdatePhone(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
	UpdateEnterprise(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
	UpdatePassword(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
	UpdateEmail(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindByUserId(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/FindByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindByEmail(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/FindByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindByPhone(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/FindByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FindByEnterprise(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/FindByEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdatePhone(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/UpdatePhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateEnterprise(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/UpdateEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdatePassword(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateEmail(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.user.User/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Add(context.Context, *AddRequest) (*pb.Response, error)
	FindByUserId(context.Context, *FindRequest) (*FindResponse, error)
	FindByEmail(context.Context, *FindRequest) (*FindResponse, error)
	FindByPhone(context.Context, *FindRequest) (*FindResponse, error)
	FindByEnterprise(context.Context, *FindRequest) (*FindResponse, error)
	UpdatePhone(context.Context, *UpdateRequest) (*pb.Response, error)
	UpdateEnterprise(context.Context, *UpdateRequest) (*pb.Response, error)
	UpdatePassword(context.Context, *UpdateRequest) (*pb.Response, error)
	UpdateEmail(context.Context, *UpdateRequest) (*pb.Response, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/FindByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindByUserId(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/FindByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindByEmail(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/FindByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindByPhone(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FindByEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FindByEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/FindByEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FindByEnterprise(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/UpdatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdatePhone(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/UpdateEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateEnterprise(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdatePassword(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.user.User/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateEmail(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _User_Add_Handler,
		},
		{
			MethodName: "FindByUserId",
			Handler:    _User_FindByUserId_Handler,
		},
		{
			MethodName: "FindByEmail",
			Handler:    _User_FindByEmail_Handler,
		},
		{
			MethodName: "FindByPhone",
			Handler:    _User_FindByPhone_Handler,
		},
		{
			MethodName: "FindByEnterprise",
			Handler:    _User_FindByEnterprise_Handler,
		},
		{
			MethodName: "UpdatePhone",
			Handler:    _User_UpdatePhone_Handler,
		},
		{
			MethodName: "UpdateEnterprise",
			Handler:    _User_UpdateEnterprise_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _User_UpdatePassword_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _User_UpdateEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/user/pb/user.proto",
}

func init() { proto.RegisterFile("base/user/pb/user.proto", fileDescriptor_c941ea4089a6591e) }

var fileDescriptor_c941ea4089a6591e = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xe1, 0x6a, 0xd4, 0x40,
	0x10, 0x26, 0xbd, 0xbb, 0xb4, 0x9d, 0x6b, 0x4b, 0x5d, 0x44, 0xd7, 0x28, 0x52, 0xce, 0x0a, 0x05,
	0x21, 0x81, 0xf3, 0xb7, 0xe0, 0x1d, 0x56, 0xc8, 0xbf, 0x12, 0xb9, 0x07, 0xd8, 0x74, 0xe7, 0x30,
	0x36, 0x97, 0x5d, 0x77, 0x37, 0x95, 0xfa, 0x90, 0x3e, 0x81, 0x4f, 0xe1, 0x13, 0xc8, 0xee, 0xa6,
	0xb9, 0xa4, 0x1c, 0xd5, 0x6b, 0x7f, 0x85, 0xf9, 0x66, 0xe6, 0xcb, 0xf7, 0xcd, 0x4c, 0x02, 0xcf,
	0x73, 0xa6, 0x31, 0xa9, 0x35, 0xaa, 0x44, 0xe6, 0xee, 0x19, 0x4b, 0x25, 0x8c, 0x20, 0x07, 0x4b,
	0x1d, 0xdb, 0x5c, 0x6c, 0xb1, 0xe8, 0xdd, 0x4f, 0x7d, 0x25, 0x99, 0xba, 0x42, 0x15, 0x5f, 0x8a,
	0x55, 0xb2, 0x14, 0x75, 0xc5, 0x99, 0x29, 0x44, 0x95, 0xb8, 0x7e, 0x99, 0xbb, 0xa7, 0x6f, 0x9d,
	0xbc, 0x85, 0xc3, 0x85, 0xe4, 0xcc, 0x60, 0x86, 0xdf, 0x6b, 0xd4, 0x86, 0x3c, 0x85, 0xd1, 0x35,
	0x2b, 0x6b, 0xa4, 0xc1, 0x49, 0x70, 0xb6, 0x9f, 0xf9, 0x60, 0xf2, 0x06, 0xc6, 0x9f, 0x8b, 0x8a,
	0xdf, 0x5f, 0xf4, 0x27, 0x80, 0x03, 0x5f, 0xa5, 0xa5, 0xa8, 0x34, 0x92, 0x53, 0x18, 0x69, 0xc3,
	0x8c, 0x2f, 0x1b, 0x4f, 0x8f, 0xe2, 0x5b, 0x9d, 0x5f, 0x2c, 0x9a, 0xf9, 0x24, 0x79, 0x06, 0xa1,
	0xd5, 0x9d, 0x72, 0xba, 0xe3, 0xd8, 0x9a, 0xc8, 0xbe, 0xa4, 0xc4, 0x6b, 0x2c, 0xe9, 0xe0, 0x24,
	0x38, 0x1b, 0x64, 0x3e, 0xb0, 0xa8, 0xfc, 0x2a, 0x2a, 0xa4, 0x43, 0xff, 0x6a, 0x17, 0x90, 0xd7,
	0x00, 0x58, 0x19, 0x54, 0x52, 0x15, 0x1a, 0xe9, 0xc8, 0xa5, 0x3a, 0x88, 0xed, 0xc2, 0x15, 0x2b,
	0x4a, 0x1a, 0xfa, 0x2e, 0x17, 0x90, 0x53, 0x38, 0x5c, 0x2a, 0xb1, 0xba, 0x50, 0xe2, 0x1b, 0x5e,
	0x9a, 0x94, 0xd3, 0x5d, 0x97, 0xed, 0x83, 0xe4, 0x15, 0xec, 0x5b, 0x60, 0x26, 0x65, 0xca, 0xe9,
	0x9e, 0xab, 0x58, 0x03, 0x93, 0x5f, 0x01, 0xc0, 0x8c, 0xb7, 0x93, 0x89, 0x60, 0x4f, 0x32, 0xad,
	0x7f, 0x08, 0xc5, 0x9b, 0xe1, 0xb4, 0xf1, 0x1d, 0x91, 0x3b, 0x9b, 0x44, 0xfe, 0xb7, 0xe1, 0xd6,
	0xd0, 0xe8, 0x5e, 0x43, 0xe1, 0x3f, 0x0d, 0xed, 0xde, 0x31, 0x34, 0xfd, 0x3d, 0x84, 0xe1, 0x42,
	0xa3, 0x22, 0x53, 0x18, 0xcc, 0x38, 0x27, 0x34, 0xee, 0x5e, 0x57, 0xbc, 0xf6, 0x1a, 0x3d, 0x69,
	0x33, 0xed, 0xc6, 0xcf, 0xfd, 0x05, 0xcc, 0x6f, 0x16, 0x7e, 0x87, 0x2f, 0xfa, 0xcd, 0x9d, 0x1b,
	0x8a, 0xa2, 0x4d, 0xa9, 0x86, 0xe6, 0x93, 0x3f, 0xb7, 0xf9, 0xcd, 0xb9, 0xb3, 0xf5, 0x58, 0x96,
	0x0b, 0x37, 0xb2, 0x07, 0xb2, 0xa4, 0x70, 0xdc, 0x68, 0x59, 0x6f, 0xea, 0x81, 0x54, 0x1f, 0x60,
	0xec, 0x3f, 0x36, 0x2f, 0xe8, 0x65, 0xbf, 0xb4, 0xf7, 0x1d, 0x6e, 0x1a, 0xee, 0x1c, 0x8e, 0x7d,
	0x4d, 0x47, 0xc9, 0xb6, 0x1c, 0x1f, 0xe1, 0xa8, 0x91, 0x70, 0x7b, 0x95, 0xdb, 0x32, 0xb4, 0x26,
	0xfc, 0x6e, 0xb6, 0x6c, 0xcf, 0x43, 0xf7, 0xdf, 0x79, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x76,
	0x4a, 0xee, 0x5b, 0xcd, 0x04, 0x00, 0x00,
}
