// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safety/blacklist/pb/blacklist.proto

package fs_safety_blacklist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlacklistClient is the client API for Blacklist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlacklistClient interface {
}

type blacklistClient struct {
	cc *grpc.ClientConn
}

func NewBlacklistClient(cc *grpc.ClientConn) BlacklistClient {
	return &blacklistClient{cc}
}

// BlacklistServer is the server API for Blacklist service.
type BlacklistServer interface {
}

func RegisterBlacklistServer(s *grpc.Server, srv BlacklistServer) {
	s.RegisterService(&_Blacklist_serviceDesc, srv)
}

var _Blacklist_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.safety.blacklist.Blacklist",
	HandlerType: (*BlacklistServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "safety/blacklist/pb/blacklist.proto",
}

func init() {
	proto.RegisterFile("safety/blacklist/pb/blacklist.proto", fileDescriptor_bc33b09e0453396d)
}

var fileDescriptor_bc33b09e0453396d = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x4e, 0x4c, 0x4b,
	0x2d, 0xa9, 0xd4, 0x4f, 0xca, 0x49, 0x4c, 0xce, 0xce, 0xc9, 0x2c, 0x2e, 0xd1, 0x2f, 0x48, 0x42,
	0x70, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0xd3, 0x8a, 0xf5, 0x20, 0xea, 0xf4, 0xe0,
	0x52, 0x46, 0xdc, 0x5c, 0x9c, 0x4e, 0x30, 0x4e, 0x12, 0x1b, 0x58, 0xa1, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xd9, 0x8b, 0xe3, 0xb9, 0x4f, 0x00, 0x00, 0x00,
}
