// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/face/pb/face.proto

package fs_base_face

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FaceToken            string   `protobuf:"bytes,2,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{0}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateRequest) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

type SearchRequest struct {
	Base64Face           string   `protobuf:"bytes,1,opt,name=base64Face,proto3" json:"base64Face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetBase64Face() string {
	if m != nil {
		return m.Base64Face
	}
	return ""
}

type SearchResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	UserId               string    `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FaceToken            string    `protobuf:"bytes,3,opt,name=faceToken,proto3" json:"faceToken,omitempty"`
	Level                int64     `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SearchResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SearchResponse) GetFaceToken() string {
	if m != nil {
		return m.FaceToken
	}
	return ""
}

func (m *SearchResponse) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

type RemoveFaceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFaceRequest) Reset()         { *m = RemoveFaceRequest{} }
func (m *RemoveFaceRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFaceRequest) ProtoMessage()    {}
func (*RemoveFaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{3}
}

func (m *RemoveFaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFaceRequest.Unmarshal(m, b)
}
func (m *RemoveFaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFaceRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFaceRequest.Merge(m, src)
}
func (m *RemoveFaceRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFaceRequest.Size(m)
}
func (m *RemoveFaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFaceRequest proto.InternalMessageInfo

func (m *RemoveFaceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AddFaceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Base64Face           string   `protobuf:"bytes,2,opt,name=base64Face,proto3" json:"base64Face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFaceRequest) Reset()         { *m = AddFaceRequest{} }
func (m *AddFaceRequest) String() string { return proto.CompactTextString(m) }
func (*AddFaceRequest) ProtoMessage()    {}
func (*AddFaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{4}
}

func (m *AddFaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFaceRequest.Unmarshal(m, b)
}
func (m *AddFaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFaceRequest.Marshal(b, m, deterministic)
}
func (m *AddFaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFaceRequest.Merge(m, src)
}
func (m *AddFaceRequest) XXX_Size() int {
	return xxx_messageInfo_AddFaceRequest.Size(m)
}
func (m *AddFaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFaceRequest proto.InternalMessageInfo

func (m *AddFaceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddFaceRequest) GetBase64Face() string {
	if m != nil {
		return m.Base64Face
	}
	return ""
}

type CompareRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Base64Face           string   `protobuf:"bytes,2,opt,name=base64Face,proto3" json:"base64Face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareRequest) Reset()         { *m = CompareRequest{} }
func (m *CompareRequest) String() string { return proto.CompactTextString(m) }
func (*CompareRequest) ProtoMessage()    {}
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62cc7a28a1bf1bca, []int{5}
}

func (m *CompareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareRequest.Unmarshal(m, b)
}
func (m *CompareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareRequest.Marshal(b, m, deterministic)
}
func (m *CompareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareRequest.Merge(m, src)
}
func (m *CompareRequest) XXX_Size() int {
	return xxx_messageInfo_CompareRequest.Size(m)
}
func (m *CompareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompareRequest proto.InternalMessageInfo

func (m *CompareRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CompareRequest) GetBase64Face() string {
	if m != nil {
		return m.Base64Face
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "fs.base.face.UpdateRequest")
	proto.RegisterType((*SearchRequest)(nil), "fs.base.face.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "fs.base.face.SearchResponse")
	proto.RegisterType((*RemoveFaceRequest)(nil), "fs.base.face.RemoveFaceRequest")
	proto.RegisterType((*AddFaceRequest)(nil), "fs.base.face.AddFaceRequest")
	proto.RegisterType((*CompareRequest)(nil), "fs.base.face.CompareRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaceClient is the client API for Face service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaceClient interface {
	// 更新人脸
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 人脸对比
	Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 在人脸库里搜索
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// 添加人脸
	AddFace(ctx context.Context, in *AddFaceRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 移除人脸
	RemoveFace(ctx context.Context, in *RemoveFaceRequest, opts ...grpc.CallOption) (*pb.Response, error)
}

type faceClient struct {
	cc *grpc.ClientConn
}

func NewFaceClient(cc *grpc.ClientConn) FaceClient {
	return &faceClient{cc}
}

func (c *faceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.face.Face/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.face.Face/Compare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/fs.base.face.Face/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) AddFace(ctx context.Context, in *AddFaceRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.face.Face/AddFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) RemoveFace(ctx context.Context, in *RemoveFaceRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.face.Face/RemoveFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceServer is the server API for Face service.
type FaceServer interface {
	// 更新人脸
	Update(context.Context, *UpdateRequest) (*pb.Response, error)
	// 人脸对比
	Compare(context.Context, *CompareRequest) (*pb.Response, error)
	// 在人脸库里搜索
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// 添加人脸
	AddFace(context.Context, *AddFaceRequest) (*pb.Response, error)
	// 移除人脸
	RemoveFace(context.Context, *RemoveFaceRequest) (*pb.Response, error)
}

func RegisterFaceServer(s *grpc.Server, srv FaceServer) {
	s.RegisterService(&_Face_serviceDesc, srv)
}

func _Face_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.face.Face/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.face.Face/Compare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Compare(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.face.Face/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_AddFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).AddFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.face.Face/AddFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).AddFace(ctx, req.(*AddFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_RemoveFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).RemoveFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.face.Face/RemoveFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).RemoveFace(ctx, req.(*RemoveFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Face_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.face.Face",
	HandlerType: (*FaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Face_Update_Handler,
		},
		{
			MethodName: "Compare",
			Handler:    _Face_Compare_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Face_Search_Handler,
		},
		{
			MethodName: "AddFace",
			Handler:    _Face_AddFace_Handler,
		},
		{
			MethodName: "RemoveFace",
			Handler:    _Face_RemoveFace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/face/pb/face.proto",
}

func init() { proto.RegisterFile("base/face/pb/face.proto", fileDescriptor_62cc7a28a1bf1bca) }

var fileDescriptor_62cc7a28a1bf1bca = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0xa5, 0xdd, 0xd6, 0x8f, 0xdd, 0xcf, 0x15, 0x16, 0x44, 0xc7, 0x1c, 0x3a, 0x8a, 0x0f, 0x83,
	0x41, 0x0a, 0x53, 0x44, 0x7c, 0x52, 0x86, 0x32, 0x5f, 0x3b, 0xfd, 0x01, 0x69, 0x7b, 0x87, 0xb2,
	0xad, 0x89, 0x4d, 0xb7, 0x07, 0x1f, 0xfd, 0x63, 0xfe, 0x35, 0x49, 0xdb, 0x6d, 0x4d, 0x57, 0x51,
	0xf0, 0x29, 0xcd, 0x3d, 0x39, 0x27, 0xe7, 0xde, 0x93, 0xc2, 0xb1, 0xcf, 0x24, 0xba, 0x33, 0x16,
	0xa0, 0x2b, 0xfc, 0x74, 0xa5, 0x22, 0xe6, 0x09, 0x27, 0x07, 0x33, 0x49, 0x15, 0x46, 0x55, 0xad,
	0x3b, 0x7c, 0x97, 0x73, 0xc1, 0xe2, 0x39, 0xc6, 0x34, 0xe0, 0x4b, 0x77, 0xc6, 0x57, 0x51, 0xc8,
	0x92, 0x57, 0x1e, 0xb9, 0x29, 0x5f, 0xf8, 0xe9, 0x9a, 0x51, 0x9d, 0x7b, 0x68, 0x3d, 0x8b, 0x90,
	0x25, 0xe8, 0xe1, 0xdb, 0x0a, 0x65, 0x42, 0x8e, 0xc0, 0x5a, 0x49, 0x8c, 0x1f, 0xc3, 0x8e, 0xd1,
	0x37, 0x06, 0x4d, 0x2f, 0xdf, 0x91, 0x1e, 0x34, 0x95, 0xfa, 0x13, 0x9f, 0x63, 0xd4, 0x31, 0x53,
	0x68, 0x57, 0x70, 0x5c, 0x68, 0x4d, 0x91, 0xc5, 0xc1, 0xcb, 0x46, 0xe6, 0x14, 0x40, 0xdd, 0x72,
	0x75, 0xf9, 0xc0, 0x02, 0xcc, 0xa5, 0x0a, 0x15, 0xe7, 0xc3, 0x00, 0x7b, 0xc3, 0x90, 0x82, 0x47,
	0x12, 0xc9, 0x39, 0x34, 0x64, 0xc2, 0x92, 0xec, 0xf4, 0xff, 0x91, 0x4d, 0x37, 0x5d, 0x4d, 0x55,
	0xd5, 0xcb, 0xc0, 0x82, 0x3f, 0xf3, 0x7b, 0x7f, 0xb5, 0x92, 0x3f, 0x72, 0x08, 0x8d, 0x05, 0xae,
	0x71, 0xd1, 0xa9, 0xf7, 0x8d, 0x41, 0xcd, 0xcb, 0x36, 0xce, 0x10, 0xda, 0x1e, 0x2e, 0xf9, 0x1a,
	0x95, 0xa5, 0x1f, 0x06, 0xe0, 0x4c, 0xc0, 0xbe, 0x0b, 0xc3, 0x5f, 0x9c, 0x2c, 0xf5, 0x6e, 0xee,
	0xf5, 0x3e, 0x01, 0x7b, 0xcc, 0x97, 0x82, 0xc5, 0x7f, 0x55, 0x1a, 0x7d, 0x9a, 0x50, 0x57, 0x1f,
	0xe4, 0x1a, 0xac, 0x2c, 0x46, 0x72, 0x42, 0x8b, 0x8f, 0x81, 0x6a, 0xe1, 0x76, 0xdb, 0x5b, 0x70,
	0x3b, 0xf5, 0x1b, 0xf8, 0x97, 0x9b, 0x21, 0x3d, 0x9d, 0xaa, 0x7b, 0xac, 0xe2, 0x8e, 0xc1, 0xca,
	0x32, 0x2c, 0xdf, 0xaa, 0xbd, 0x85, 0x6e, 0xaf, 0x1a, 0xdc, 0x19, 0xc8, 0xe7, 0x5a, 0x36, 0xa0,
	0x8f, 0xbb, 0xca, 0xc0, 0x2d, 0xc0, 0x2e, 0x40, 0x72, 0xa6, 0xd3, 0xf7, 0xa2, 0xad, 0x50, 0xf0,
	0xad, 0xf4, 0x37, 0xb8, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x5a, 0x65, 0xf1, 0x5c, 0x03,
	0x00, 0x00,
}
