// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/project/pb/project.proto

package fs_base_project

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnablePlatformRequest struct {
	Platform             int64    `protobuf:"varint,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Enable               bool     `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	Meta                 *pb.Meta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnablePlatformRequest) Reset()         { *m = EnablePlatformRequest{} }
func (m *EnablePlatformRequest) String() string { return proto.CompactTextString(m) }
func (*EnablePlatformRequest) ProtoMessage()    {}
func (*EnablePlatformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{0}
}

func (m *EnablePlatformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnablePlatformRequest.Unmarshal(m, b)
}
func (m *EnablePlatformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnablePlatformRequest.Marshal(b, m, deterministic)
}
func (m *EnablePlatformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnablePlatformRequest.Merge(m, src)
}
func (m *EnablePlatformRequest) XXX_Size() int {
	return xxx_messageInfo_EnablePlatformRequest.Size(m)
}
func (m *EnablePlatformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnablePlatformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnablePlatformRequest proto.InternalMessageInfo

func (m *EnablePlatformRequest) GetPlatform() int64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *EnablePlatformRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *EnablePlatformRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type GetResponse struct {
	State                *pb.State           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Info                 *ProjectInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Strategy             *pb.ProjectStrategy `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetResponse) GetInfo() *ProjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetResponse) GetStrategy() *pb.ProjectStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type NewRequest struct {
	Logo                 string   `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	En                   string   `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Zh                   string   `protobuf:"bytes,4,opt,name=zh,proto3" json:"zh,omitempty"`
	Meta                 *pb.Meta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRequest) Reset()         { *m = NewRequest{} }
func (m *NewRequest) String() string { return proto.CompactTextString(m) }
func (*NewRequest) ProtoMessage()    {}
func (*NewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{3}
}

func (m *NewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRequest.Unmarshal(m, b)
}
func (m *NewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRequest.Marshal(b, m, deterministic)
}
func (m *NewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRequest.Merge(m, src)
}
func (m *NewRequest) XXX_Size() int {
	return xxx_messageInfo_NewRequest.Size(m)
}
func (m *NewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRequest proto.InternalMessageInfo

func (m *NewRequest) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *NewRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *NewRequest) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *NewRequest) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *NewRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ProjectInfo struct {
	Logo                 string    `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc                 string    `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	En                   string    `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Zh                   string    `protobuf:"bytes,4,opt,name=zh,proto3" json:"zh,omitempty"`
	Platform             *Platform `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Level                int64     `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProjectInfo) Reset()         { *m = ProjectInfo{} }
func (m *ProjectInfo) String() string { return proto.CompactTextString(m) }
func (*ProjectInfo) ProtoMessage()    {}
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{4}
}

func (m *ProjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInfo.Unmarshal(m, b)
}
func (m *ProjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInfo.Marshal(b, m, deterministic)
}
func (m *ProjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfo.Merge(m, src)
}
func (m *ProjectInfo) XXX_Size() int {
	return xxx_messageInfo_ProjectInfo.Size(m)
}
func (m *ProjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfo proto.InternalMessageInfo

func (m *ProjectInfo) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *ProjectInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ProjectInfo) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *ProjectInfo) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

func (m *ProjectInfo) GetPlatform() *Platform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ProjectInfo) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

type Platform struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Platform             int64    `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Platform) Reset()         { *m = Platform{} }
func (m *Platform) String() string { return proto.CompactTextString(m) }
func (*Platform) ProtoMessage()    {}
func (*Platform) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee2cafb576e5e1c, []int{5}
}

func (m *Platform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Platform.Unmarshal(m, b)
}
func (m *Platform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Platform.Marshal(b, m, deterministic)
}
func (m *Platform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Platform.Merge(m, src)
}
func (m *Platform) XXX_Size() int {
	return xxx_messageInfo_Platform.Size(m)
}
func (m *Platform) XXX_DiscardUnknown() {
	xxx_messageInfo_Platform.DiscardUnknown(m)
}

var xxx_messageInfo_Platform proto.InternalMessageInfo

func (m *Platform) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Platform) GetPlatform() int64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func init() {
	proto.RegisterType((*EnablePlatformRequest)(nil), "fs.base.project.EnablePlatformRequest")
	proto.RegisterType((*GetRequest)(nil), "fs.base.project.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "fs.base.project.GetResponse")
	proto.RegisterType((*NewRequest)(nil), "fs.base.project.NewRequest")
	proto.RegisterType((*ProjectInfo)(nil), "fs.base.project.ProjectInfo")
	proto.RegisterType((*Platform)(nil), "fs.base.project.Platform")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectClient is the client API for Project service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectClient interface {
	// http
	New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// gRPC inside
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// http provider
	EnablePlatform(ctx context.Context, in *EnablePlatformRequest, opts ...grpc.CallOption) (*pb.Response, error)
}

type projectClient struct {
	cc *grpc.ClientConn
}

func NewProjectClient(cc *grpc.ClientConn) ProjectClient {
	return &projectClient{cc}
}

func (c *projectClient) New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.project.Project/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/fs.base.project.Project/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectClient) EnablePlatform(ctx context.Context, in *EnablePlatformRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.project.Project/EnablePlatform", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServer is the server API for Project service.
type ProjectServer interface {
	// http
	New(context.Context, *NewRequest) (*pb.Response, error)
	// gRPC inside
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// http provider
	EnablePlatform(context.Context, *EnablePlatformRequest) (*pb.Response, error)
}

func RegisterProjectServer(s *grpc.Server, srv ProjectServer) {
	s.RegisterService(&_Project_serviceDesc, srv)
}

func _Project_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.project.Project/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServer).New(ctx, req.(*NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Project_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.project.Project/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Project_EnablePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServer).EnablePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.project.Project/EnablePlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServer).EnablePlatform(ctx, req.(*EnablePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Project_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.project.Project",
	HandlerType: (*ProjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Project_New_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Project_Get_Handler,
		},
		{
			MethodName: "EnablePlatform",
			Handler:    _Project_EnablePlatform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/project/pb/project.proto",
}

func init() { proto.RegisterFile("base/project/pb/project.proto", fileDescriptor_eee2cafb576e5e1c) }

var fileDescriptor_eee2cafb576e5e1c = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xfa, 0x47, 0x7a, 0x22, 0x8a, 0xb0, 0x00, 0x85, 0x30, 0xa4, 0x12, 0x21, 0x14, 0x09,
	0x29, 0x19, 0x81, 0xdd, 0x23, 0x24, 0x34, 0x4d, 0x88, 0x69, 0xf2, 0x9e, 0xc0, 0x49, 0x4f, 0xb6,
	0xb2, 0xd4, 0x0e, 0xb1, 0x47, 0x45, 0x5f, 0x85, 0x3b, 0x5e, 0x88, 0x57, 0x42, 0x71, 0x1c, 0xb7,
	0xa5, 0x01, 0x6e, 0x76, 0x65, 0x7f, 0xe7, 0x7c, 0xc7, 0xe7, 0xc7, 0xdf, 0x81, 0xe7, 0x19, 0x93,
	0x98, 0x54, 0xb5, 0xf8, 0x82, 0xb9, 0x4a, 0xaa, 0xac, 0xbb, 0xc6, 0x55, 0x2d, 0x94, 0x20, 0x0f,
	0x0a, 0x19, 0x37, 0x8c, 0xd8, 0x98, 0x83, 0xd7, 0x1b, 0x79, 0x53, 0xb1, 0xfa, 0x06, 0xeb, 0x38,
	0x17, 0xab, 0xa4, 0x10, 0xb7, 0x7c, 0xc1, 0xd4, 0x52, 0xf0, 0xa4, 0x7d, 0x28, 0x4b, 0x3a, 0xba,
	0x12, 0xc1, 0xf1, 0x7f, 0xc9, 0x52, 0xd5, 0x4c, 0xe1, 0xd5, 0xf7, 0x37, 0x6d, 0x44, 0xc8, 0xe1,
	0xf1, 0x47, 0xce, 0xb2, 0x12, 0x2f, 0x4a, 0xa6, 0x0a, 0x51, 0xaf, 0x28, 0x7e, 0xbd, 0x45, 0xa9,
	0x48, 0x00, 0x6e, 0x65, 0x4c, 0xbe, 0x33, 0x77, 0xa2, 0x21, 0xb5, 0x98, 0x3c, 0x81, 0x09, 0xea,
	0x20, 0x7f, 0x30, 0x77, 0x22, 0x97, 0x1a, 0x44, 0x5e, 0xc0, 0x68, 0x85, 0x8a, 0xf9, 0xc3, 0xb9,
	0x13, 0x79, 0xe9, 0xfd, 0xb8, 0xeb, 0xe5, 0x33, 0x2a, 0x46, 0xb5, 0x2b, 0x8c, 0x00, 0x4e, 0x51,
	0xed, 0x24, 0xc9, 0xcb, 0x25, 0x72, 0x75, 0xb6, 0xd0, 0x49, 0xa6, 0xd4, 0xe2, 0xf0, 0x87, 0x03,
	0x9e, 0xa6, 0xca, 0x4a, 0x70, 0x89, 0xe4, 0x25, 0x8c, 0xa5, 0x62, 0x0a, 0x35, 0xd1, 0x4b, 0x67,
	0xf6, 0xf5, 0xcb, 0xc6, 0x4a, 0x5b, 0x27, 0x39, 0x86, 0xd1, 0x92, 0x17, 0x42, 0x17, 0xe6, 0xa5,
	0x47, 0xf1, 0x1f, 0xe3, 0x8c, 0x2f, 0xda, 0xf3, 0x8c, 0x17, 0x82, 0x6a, 0x26, 0x79, 0x07, 0x6e,
	0x37, 0x14, 0x53, 0xb8, 0x6f, 0xa3, 0x0c, 0xfb, 0xd2, 0xf8, 0xa9, 0x65, 0x86, 0x6b, 0x80, 0x73,
	0x5c, 0x77, 0x7d, 0x10, 0x18, 0x95, 0xe2, 0x4a, 0x98, 0x1e, 0xf4, 0xbd, 0xb1, 0x2d, 0x50, 0xe6,
	0xba, 0x92, 0x29, 0xd5, 0x77, 0x32, 0x83, 0x01, 0x72, 0x9d, 0x65, 0x4a, 0x07, 0xc8, 0x1b, 0xbc,
	0xb9, 0xf6, 0x47, 0x2d, 0xde, 0x5c, 0xdb, 0x01, 0x8e, 0xff, 0x3e, 0xc0, 0x9f, 0x0e, 0x78, 0x3b,
	0x4d, 0xdc, 0x59, 0xea, 0x93, 0x9d, 0xff, 0x6e, 0xd3, 0x3f, 0x3d, 0x1c, 0x5e, 0xa7, 0x91, 0xad,
	0x14, 0x1e, 0xc1, 0xb8, 0xc4, 0x6f, 0x58, 0xfa, 0x13, 0xad, 0x91, 0x16, 0x84, 0x1f, 0xc0, 0xed,
	0xb8, 0xff, 0xfa, 0xe3, 0x3d, 0x91, 0x0d, 0xf6, 0x45, 0x96, 0xfe, 0x72, 0xe0, 0x9e, 0x69, 0x94,
	0x9c, 0xc0, 0xf0, 0x1c, 0xd7, 0xe4, 0xd9, 0x41, 0x45, 0xdb, 0x3f, 0x08, 0x1e, 0x5a, 0xa7, 0x95,
	0xcc, 0x7b, 0x18, 0x9e, 0xa2, 0xea, 0x09, 0xdb, 0x4a, 0x30, 0x38, 0xea, 0x77, 0x9a, 0x17, 0x3e,
	0xc1, 0x6c, 0x7f, 0x3d, 0xc8, 0xab, 0x03, 0x7e, 0xef, 0xfe, 0xf4, 0x94, 0x93, 0x4d, 0xf4, 0xca,
	0xbd, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x92, 0xad, 0xd1, 0xe1, 0x03, 0x04, 0x00, 0x00,
}
