// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/pb/base.proto

package fs_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 作为API请求用，放在body里
type Meta struct {
	Face                 string   `protobuf:"bytes,1,opt,name=face,proto3" json:"face,omitempty"`
	Longitude            string   `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             string   `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Validate             string   `protobuf:"bytes,4,opt,name=validate,proto3" json:"validate,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *Meta) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Meta) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Meta) GetValidate() string {
	if m != nil {
		return m.Validate
	}
	return ""
}

func (m *Meta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type State struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{1}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *State) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *State) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Response) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 作为服务间传输用
type Metadata struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Ip                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Device               string   `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	UserAgent            string   `protobuf:"bytes,6,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Platform             int64    `protobuf:"varint,7,opt,name=platform,proto3" json:"platform,omitempty"`
	Api                  string   `protobuf:"bytes,8,opt,name=api,proto3" json:"api,omitempty"`
	Level                int64    `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	Token                string   `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	Session              string   `protobuf:"bytes,11,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{3}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Metadata) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Metadata) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Metadata) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Metadata) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Metadata) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Metadata) GetPlatform() int64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Metadata) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Metadata) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Metadata) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Metadata) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 int64    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Must                 bool     `protobuf:"varint,4,opt,name=must,proto3" json:"must,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{4}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KeyValue) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *KeyValue) GetMust() bool {
	if m != nil {
		return m.Must
	}
	return false
}

type DirectMessage struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectMessage) Reset()         { *m = DirectMessage{} }
func (m *DirectMessage) String() string { return proto.CompactTextString(m) }
func (*DirectMessage) ProtoMessage()    {}
func (*DirectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d99073f0a37c125, []int{5}
}

func (m *DirectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectMessage.Unmarshal(m, b)
}
func (m *DirectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectMessage.Marshal(b, m, deterministic)
}
func (m *DirectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectMessage.Merge(m, src)
}
func (m *DirectMessage) XXX_Size() int {
	return xxx_messageInfo_DirectMessage.Size(m)
}
func (m *DirectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DirectMessage proto.InternalMessageInfo

func (m *DirectMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DirectMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Meta)(nil), "fs.base.Meta")
	proto.RegisterType((*State)(nil), "fs.base.State")
	proto.RegisterType((*Response)(nil), "fs.base.Response")
	proto.RegisterType((*Metadata)(nil), "fs.base.Metadata")
	proto.RegisterType((*KeyValue)(nil), "fs.base.KeyValue")
	proto.RegisterType((*DirectMessage)(nil), "fs.base.DirectMessage")
}

func init() { proto.RegisterFile("base/pb/base.proto", fileDescriptor_0d99073f0a37c125) }

var fileDescriptor_0d99073f0a37c125 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbf, 0xaf, 0x13, 0x31,
	0x0c, 0xc7, 0xd5, 0xeb, 0xaf, 0xab, 0x9f, 0x78, 0x42, 0x11, 0x42, 0x11, 0x62, 0x40, 0x27, 0x06,
	0xa6, 0x3e, 0x09, 0x26, 0x46, 0x24, 0x18, 0x1e, 0xe8, 0x2d, 0x87, 0xc4, 0xc0, 0x96, 0x5e, 0xdc,
	0x2a, 0x34, 0xbd, 0x44, 0x17, 0xf7, 0xa4, 0x6e, 0xfc, 0x15, 0xfc, 0xbd, 0xc8, 0x4e, 0xee, 0x98,
	0x98, 0xea, 0xaf, 0xbf, 0x3e, 0xdb, 0xf9, 0xb8, 0xa0, 0x0e, 0x26, 0xe1, 0x43, 0x3c, 0x3c, 0xf0,
	0xef, 0x3e, 0x0e, 0x81, 0x82, 0xda, 0x1e, 0xd3, 0x9e, 0x65, 0xf3, 0x7b, 0x01, 0xab, 0x27, 0x24,
	0xa3, 0x14, 0xac, 0x8e, 0xa6, 0x43, 0xbd, 0x78, 0xb3, 0x78, 0xb7, 0x6b, 0x25, 0x56, 0xaf, 0x61,
	0xe7, 0x43, 0x7f, 0x72, 0x74, 0xb5, 0xa8, 0x2b, 0x31, 0xfe, 0x25, 0xd4, 0x2b, 0xa8, 0xbd, 0xa1,
	0x6c, 0x2e, 0xc5, 0x9c, 0x35, 0x7b, 0xa3, 0xf1, 0xce, 0x1a, 0x42, 0xbd, 0xca, 0xde, 0xa4, 0xd5,
	0x3d, 0x54, 0xce, 0xea, 0xb5, 0x64, 0x2b, 0x67, 0x9b, 0x2f, 0xb0, 0xfe, 0x4e, 0x6c, 0x28, 0x58,
	0x75, 0xc1, 0xe6, 0x15, 0x96, 0xad, 0xc4, 0x5c, 0x1c, 0xce, 0x32, 0xbb, 0x6e, 0xab, 0x70, 0x56,
	0x1a, 0xb6, 0x17, 0x4c, 0xc9, 0x9c, 0xa6, 0x99, 0x93, 0x6c, 0xbe, 0x42, 0xdd, 0x62, 0x8a, 0xa1,
	0x4f, 0xa8, 0xde, 0xc2, 0x3a, 0x71, 0x4b, 0x69, 0x75, 0xf7, 0xfe, 0x7e, 0x5f, 0x9e, 0xbb, 0x97,
	0x41, 0x6d, 0x36, 0xb9, 0x57, 0x17, 0x7a, 0xc2, 0x9e, 0xca, 0xe3, 0x26, 0xd9, 0xfc, 0xa9, 0xa0,
	0x66, 0x2a, 0xd6, 0x90, 0xe1, 0xb7, 0x74, 0xde, 0x61, 0x4f, 0x8f, 0xb6, 0xd0, 0x99, 0x35, 0x13,
	0x8a, 0x43, 0xf8, 0x85, 0x1d, 0x9b, 0x85, 0xd0, 0x9c, 0x50, 0x2f, 0x61, 0x73, 0x4d, 0x38, 0x3c,
	0xda, 0xb2, 0x6b, 0x51, 0x42, 0x20, 0x16, 0x2e, 0x95, 0x8b, 0x5c, 0x67, 0x71, 0x74, 0x1d, 0x16,
	0x2a, 0x45, 0x71, 0x77, 0xfe, 0xe2, 0xd3, 0x89, 0x57, 0xdc, 0xe4, 0xee, 0x73, 0x82, 0xf7, 0x8a,
	0xde, 0xd0, 0x31, 0x0c, 0x17, 0xbd, 0x15, 0x64, 0xb3, 0x56, 0xcf, 0x61, 0x69, 0xa2, 0xd3, 0xb5,
	0x7c, 0xc3, 0xa1, 0x7a, 0x01, 0x6b, 0x8f, 0x23, 0x7a, 0xbd, 0x93, 0xd2, 0x2c, 0x38, 0x4b, 0xe1,
	0x8c, 0xbd, 0x06, 0xa9, 0xcc, 0x82, 0xc1, 0x24, 0x4c, 0xc9, 0x85, 0x5e, 0xdf, 0x65, 0x30, 0x45,
	0x36, 0x3f, 0xa1, 0xfe, 0x86, 0xb7, 0x1f, 0xc6, 0x5f, 0x91, 0x67, 0x9c, 0xf1, 0x56, 0x90, 0x70,
	0xc8, 0xdd, 0x46, 0xb6, 0x0a, 0x89, 0x2c, 0xf8, 0xac, 0x74, 0x8b, 0xf9, 0x5e, 0xcb, 0x56, 0x62,
	0xce, 0x5d, 0xae, 0x89, 0x84, 0x41, 0xdd, 0x4a, 0xdc, 0x7c, 0x84, 0x67, 0x9f, 0xdd, 0x80, 0x1d,
	0x3d, 0xe5, 0x8b, 0x32, 0x26, 0x0a, 0xa5, 0x7f, 0x45, 0xe1, 0xff, 0xf7, 0x3a, 0x6c, 0xe4, 0x5f,
	0xfd, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x3d, 0x37, 0x83, 0xeb, 0x02, 0x00, 0x00,
}
