// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/pb/strategy1.proto

package fs_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectStrategy struct {
	// 以下不用提交
	ProjectId            string         `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Creator              string         `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateAt             int64          `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	ModifyAt             int64          `protobuf:"varint,4,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"`
	Version              int64          `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Events               *Events        `protobuf:"bytes,6,opt,name=events,proto3" json:"events,omitempty"`
	Configuration        *Configuration `protobuf:"bytes,7,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProjectStrategy) Reset()         { *m = ProjectStrategy{} }
func (m *ProjectStrategy) String() string { return proto.CompactTextString(m) }
func (*ProjectStrategy) ProtoMessage()    {}
func (*ProjectStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{0}
}

func (m *ProjectStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectStrategy.Unmarshal(m, b)
}
func (m *ProjectStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectStrategy.Marshal(b, m, deterministic)
}
func (m *ProjectStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectStrategy.Merge(m, src)
}
func (m *ProjectStrategy) XXX_Size() int {
	return xxx_messageInfo_ProjectStrategy.Size(m)
}
func (m *ProjectStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectStrategy proto.InternalMessageInfo

func (m *ProjectStrategy) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ProjectStrategy) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ProjectStrategy) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *ProjectStrategy) GetModifyAt() int64 {
	if m != nil {
		return m.ModifyAt
	}
	return 0
}

func (m *ProjectStrategy) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProjectStrategy) GetEvents() *Events {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ProjectStrategy) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type Configuration struct {
	RegisterReviewId     string   `protobuf:"bytes,1,opt,name=registerReviewId,proto3" json:"registerReviewId,omitempty"`
	OpenTime             string   `protobuf:"bytes,2,opt,name=openTime,proto3" json:"openTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{1}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetRegisterReviewId() string {
	if m != nil {
		return m.RegisterReviewId
	}
	return ""
}

func (m *Configuration) GetOpenTime() string {
	if m != nil {
		return m.OpenTime
	}
	return ""
}

type Events struct {
	OnRegister               *OnRegister               `protobuf:"bytes,1,opt,name=onRegister,proto3" json:"onRegister,omitempty"`
	OnLogin                  *OnLogin                  `protobuf:"bytes,2,opt,name=onLogin,proto3" json:"onLogin,omitempty"`
	OnVerification           *OnVerification           `protobuf:"bytes,3,opt,name=onVerification,proto3" json:"onVerification,omitempty"`
	OnQRLogin                *OnQRLogin                `protobuf:"bytes,4,opt,name=onQRLogin,proto3" json:"onQRLogin,omitempty"`
	OnFaceLogin              *OnFaceLogin              `protobuf:"bytes,5,opt,name=onFaceLogin,proto3" json:"onFaceLogin,omitempty"`
	OnCommonEquipmentChanges *OnCommonEquipmentChanges `protobuf:"bytes,6,opt,name=OnCommonEquipmentChanges,proto3" json:"OnCommonEquipmentChanges,omitempty"`
	OnRequestFrozen          *OnRequestFrozen          `protobuf:"bytes,7,opt,name=onRequestFrozen,proto3" json:"onRequestFrozen,omitempty"`
	OnCancelFrozen           *OnCancelFrozen           `protobuf:"bytes,8,opt,name=onCancelFrozen,proto3" json:"onCancelFrozen,omitempty"`
	OnChangePhoneNumber      *OnChangePhoneNumber      `protobuf:"bytes,9,opt,name=onChangePhoneNumber,proto3" json:"onChangePhoneNumber,omitempty"`
	OnChangeEmail            *OnChangeEmail            `protobuf:"bytes,10,opt,name=onChangeEmail,proto3" json:"onChangeEmail,omitempty"`
	OnChangeOAuth            *OnChangeOAuth            `protobuf:"bytes,11,opt,name=onChangeOAuth,proto3" json:"onChangeOAuth,omitempty"`
	OnChangeFace             *OnChangeFace             `protobuf:"bytes,12,opt,name=onChangeFace,proto3" json:"onChangeFace,omitempty"`
	OnResetPassword          *OnResetPassword          `protobuf:"bytes,13,opt,name=onResetPassword,proto3" json:"onResetPassword,omitempty"`
	OnElsewhereLogin         *OnElsewhereLogin         `protobuf:"bytes,14,opt,name=onElsewhereLogin,proto3" json:"onElsewhereLogin,omitempty"`
	OnSubmitReview           *OnSubmitReview           `protobuf:"bytes,15,opt,name=onSubmitReview,proto3" json:"onSubmitReview,omitempty"`
	OnInviteUser             *OnInviteUser             `protobuf:"bytes,16,opt,name=onInviteUser,proto3" json:"onInviteUser,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{2}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetOnRegister() *OnRegister {
	if m != nil {
		return m.OnRegister
	}
	return nil
}

func (m *Events) GetOnLogin() *OnLogin {
	if m != nil {
		return m.OnLogin
	}
	return nil
}

func (m *Events) GetOnVerification() *OnVerification {
	if m != nil {
		return m.OnVerification
	}
	return nil
}

func (m *Events) GetOnQRLogin() *OnQRLogin {
	if m != nil {
		return m.OnQRLogin
	}
	return nil
}

func (m *Events) GetOnFaceLogin() *OnFaceLogin {
	if m != nil {
		return m.OnFaceLogin
	}
	return nil
}

func (m *Events) GetOnCommonEquipmentChanges() *OnCommonEquipmentChanges {
	if m != nil {
		return m.OnCommonEquipmentChanges
	}
	return nil
}

func (m *Events) GetOnRequestFrozen() *OnRequestFrozen {
	if m != nil {
		return m.OnRequestFrozen
	}
	return nil
}

func (m *Events) GetOnCancelFrozen() *OnCancelFrozen {
	if m != nil {
		return m.OnCancelFrozen
	}
	return nil
}

func (m *Events) GetOnChangePhoneNumber() *OnChangePhoneNumber {
	if m != nil {
		return m.OnChangePhoneNumber
	}
	return nil
}

func (m *Events) GetOnChangeEmail() *OnChangeEmail {
	if m != nil {
		return m.OnChangeEmail
	}
	return nil
}

func (m *Events) GetOnChangeOAuth() *OnChangeOAuth {
	if m != nil {
		return m.OnChangeOAuth
	}
	return nil
}

func (m *Events) GetOnChangeFace() *OnChangeFace {
	if m != nil {
		return m.OnChangeFace
	}
	return nil
}

func (m *Events) GetOnResetPassword() *OnResetPassword {
	if m != nil {
		return m.OnResetPassword
	}
	return nil
}

func (m *Events) GetOnElsewhereLogin() *OnElsewhereLogin {
	if m != nil {
		return m.OnElsewhereLogin
	}
	return nil
}

func (m *Events) GetOnSubmitReview() *OnSubmitReview {
	if m != nil {
		return m.OnSubmitReview
	}
	return nil
}

func (m *Events) GetOnInviteUser() *OnInviteUser {
	if m != nil {
		return m.OnInviteUser
	}
	return nil
}

// 邀请用户时
type OnInviteUser struct {
	ExpireTime           int64    `protobuf:"varint,1,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Review               int64    `protobuf:"varint,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnInviteUser) Reset()         { *m = OnInviteUser{} }
func (m *OnInviteUser) String() string { return proto.CompactTextString(m) }
func (*OnInviteUser) ProtoMessage()    {}
func (*OnInviteUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{3}
}

func (m *OnInviteUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnInviteUser.Unmarshal(m, b)
}
func (m *OnInviteUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnInviteUser.Marshal(b, m, deterministic)
}
func (m *OnInviteUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnInviteUser.Merge(m, src)
}
func (m *OnInviteUser) XXX_Size() int {
	return xxx_messageInfo_OnInviteUser.Size(m)
}
func (m *OnInviteUser) XXX_DiscardUnknown() {
	xxx_messageInfo_OnInviteUser.DiscardUnknown(m)
}

var xxx_messageInfo_OnInviteUser proto.InternalMessageInfo

func (m *OnInviteUser) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *OnInviteUser) GetReview() int64 {
	if m != nil {
		return m.Review
	}
	return 0
}

// 提交审核时
type OnSubmitReview struct {
	ReportUserId         string   `protobuf:"bytes,1,opt,name=reportUserId,proto3" json:"reportUserId,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,2,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnSubmitReview) Reset()         { *m = OnSubmitReview{} }
func (m *OnSubmitReview) String() string { return proto.CompactTextString(m) }
func (*OnSubmitReview) ProtoMessage()    {}
func (*OnSubmitReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{4}
}

func (m *OnSubmitReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnSubmitReview.Unmarshal(m, b)
}
func (m *OnSubmitReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnSubmitReview.Marshal(b, m, deterministic)
}
func (m *OnSubmitReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnSubmitReview.Merge(m, src)
}
func (m *OnSubmitReview) XXX_Size() int {
	return xxx_messageInfo_OnSubmitReview.Size(m)
}
func (m *OnSubmitReview) XXX_DiscardUnknown() {
	xxx_messageInfo_OnSubmitReview.DiscardUnknown(m)
}

var xxx_messageInfo_OnSubmitReview proto.InternalMessageInfo

func (m *OnSubmitReview) GetReportUserId() string {
	if m != nil {
		return m.ReportUserId
	}
	return ""
}

func (m *OnSubmitReview) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

// 异地登录
type OnElsewhereLogin struct {
	SendMessageToUser    int64    `protobuf:"varint,1,opt,name=sendMessageToUser,proto3" json:"sendMessageToUser,omitempty"`
	Verification         int64    `protobuf:"varint,2,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnElsewhereLogin) Reset()         { *m = OnElsewhereLogin{} }
func (m *OnElsewhereLogin) String() string { return proto.CompactTextString(m) }
func (*OnElsewhereLogin) ProtoMessage()    {}
func (*OnElsewhereLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{5}
}

func (m *OnElsewhereLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnElsewhereLogin.Unmarshal(m, b)
}
func (m *OnElsewhereLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnElsewhereLogin.Marshal(b, m, deterministic)
}
func (m *OnElsewhereLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnElsewhereLogin.Merge(m, src)
}
func (m *OnElsewhereLogin) XXX_Size() int {
	return xxx_messageInfo_OnElsewhereLogin.Size(m)
}
func (m *OnElsewhereLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OnElsewhereLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OnElsewhereLogin proto.InternalMessageInfo

func (m *OnElsewhereLogin) GetSendMessageToUser() int64 {
	if m != nil {
		return m.SendMessageToUser
	}
	return 0
}

func (m *OnElsewhereLogin) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

// 重置密码时
type OnResetPassword struct {
	Phone                int64    `protobuf:"varint,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                int64    `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnResetPassword) Reset()         { *m = OnResetPassword{} }
func (m *OnResetPassword) String() string { return proto.CompactTextString(m) }
func (*OnResetPassword) ProtoMessage()    {}
func (*OnResetPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{6}
}

func (m *OnResetPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnResetPassword.Unmarshal(m, b)
}
func (m *OnResetPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnResetPassword.Marshal(b, m, deterministic)
}
func (m *OnResetPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnResetPassword.Merge(m, src)
}
func (m *OnResetPassword) XXX_Size() int {
	return xxx_messageInfo_OnResetPassword.Size(m)
}
func (m *OnResetPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_OnResetPassword.DiscardUnknown(m)
}

var xxx_messageInfo_OnResetPassword proto.InternalMessageInfo

func (m *OnResetPassword) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *OnResetPassword) GetEmail() int64 {
	if m != nil {
		return m.Email
	}
	return 0
}

// 改变手机号
type OnChangePhoneNumber struct {
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnChangePhoneNumber) Reset()         { *m = OnChangePhoneNumber{} }
func (m *OnChangePhoneNumber) String() string { return proto.CompactTextString(m) }
func (*OnChangePhoneNumber) ProtoMessage()    {}
func (*OnChangePhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{7}
}

func (m *OnChangePhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnChangePhoneNumber.Unmarshal(m, b)
}
func (m *OnChangePhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnChangePhoneNumber.Marshal(b, m, deterministic)
}
func (m *OnChangePhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnChangePhoneNumber.Merge(m, src)
}
func (m *OnChangePhoneNumber) XXX_Size() int {
	return xxx_messageInfo_OnChangePhoneNumber.Size(m)
}
func (m *OnChangePhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_OnChangePhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_OnChangePhoneNumber proto.InternalMessageInfo

func (m *OnChangePhoneNumber) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

// 改变邮箱
type OnChangeEmail struct {
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnChangeEmail) Reset()         { *m = OnChangeEmail{} }
func (m *OnChangeEmail) String() string { return proto.CompactTextString(m) }
func (*OnChangeEmail) ProtoMessage()    {}
func (*OnChangeEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{8}
}

func (m *OnChangeEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnChangeEmail.Unmarshal(m, b)
}
func (m *OnChangeEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnChangeEmail.Marshal(b, m, deterministic)
}
func (m *OnChangeEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnChangeEmail.Merge(m, src)
}
func (m *OnChangeEmail) XXX_Size() int {
	return xxx_messageInfo_OnChangeEmail.Size(m)
}
func (m *OnChangeEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_OnChangeEmail.DiscardUnknown(m)
}

var xxx_messageInfo_OnChangeEmail proto.InternalMessageInfo

func (m *OnChangeEmail) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

// 改变第三方账号
type OnChangeOAuth struct {
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnChangeOAuth) Reset()         { *m = OnChangeOAuth{} }
func (m *OnChangeOAuth) String() string { return proto.CompactTextString(m) }
func (*OnChangeOAuth) ProtoMessage()    {}
func (*OnChangeOAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{9}
}

func (m *OnChangeOAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnChangeOAuth.Unmarshal(m, b)
}
func (m *OnChangeOAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnChangeOAuth.Marshal(b, m, deterministic)
}
func (m *OnChangeOAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnChangeOAuth.Merge(m, src)
}
func (m *OnChangeOAuth) XXX_Size() int {
	return xxx_messageInfo_OnChangeOAuth.Size(m)
}
func (m *OnChangeOAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_OnChangeOAuth.DiscardUnknown(m)
}

var xxx_messageInfo_OnChangeOAuth proto.InternalMessageInfo

func (m *OnChangeOAuth) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

// 改变脸部验证
type OnChangeFace struct {
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnChangeFace) Reset()         { *m = OnChangeFace{} }
func (m *OnChangeFace) String() string { return proto.CompactTextString(m) }
func (*OnChangeFace) ProtoMessage()    {}
func (*OnChangeFace) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{10}
}

func (m *OnChangeFace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnChangeFace.Unmarshal(m, b)
}
func (m *OnChangeFace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnChangeFace.Marshal(b, m, deterministic)
}
func (m *OnChangeFace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnChangeFace.Merge(m, src)
}
func (m *OnChangeFace) XXX_Size() int {
	return xxx_messageInfo_OnChangeFace.Size(m)
}
func (m *OnChangeFace) XXX_DiscardUnknown() {
	xxx_messageInfo_OnChangeFace.DiscardUnknown(m)
}

var xxx_messageInfo_OnChangeFace proto.InternalMessageInfo

func (m *OnChangeFace) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

// 请求冻结
type OnRequestFrozen struct {
	// repeated fs.base.KeyValue kvs = 1; //需要提交的信息
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	SubmitInfo           int64    `protobuf:"varint,2,opt,name=submitInfo,proto3" json:"submitInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnRequestFrozen) Reset()         { *m = OnRequestFrozen{} }
func (m *OnRequestFrozen) String() string { return proto.CompactTextString(m) }
func (*OnRequestFrozen) ProtoMessage()    {}
func (*OnRequestFrozen) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{11}
}

func (m *OnRequestFrozen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRequestFrozen.Unmarshal(m, b)
}
func (m *OnRequestFrozen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRequestFrozen.Marshal(b, m, deterministic)
}
func (m *OnRequestFrozen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRequestFrozen.Merge(m, src)
}
func (m *OnRequestFrozen) XXX_Size() int {
	return xxx_messageInfo_OnRequestFrozen.Size(m)
}
func (m *OnRequestFrozen) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRequestFrozen.DiscardUnknown(m)
}

var xxx_messageInfo_OnRequestFrozen proto.InternalMessageInfo

func (m *OnRequestFrozen) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

func (m *OnRequestFrozen) GetSubmitInfo() int64 {
	if m != nil {
		return m.SubmitInfo
	}
	return 0
}

// 解除冻结
type OnCancelFrozen struct {
	Verification         int64    `protobuf:"varint,1,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCancelFrozen) Reset()         { *m = OnCancelFrozen{} }
func (m *OnCancelFrozen) String() string { return proto.CompactTextString(m) }
func (*OnCancelFrozen) ProtoMessage()    {}
func (*OnCancelFrozen) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{12}
}

func (m *OnCancelFrozen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCancelFrozen.Unmarshal(m, b)
}
func (m *OnCancelFrozen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCancelFrozen.Marshal(b, m, deterministic)
}
func (m *OnCancelFrozen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCancelFrozen.Merge(m, src)
}
func (m *OnCancelFrozen) XXX_Size() int {
	return xxx_messageInfo_OnCancelFrozen.Size(m)
}
func (m *OnCancelFrozen) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCancelFrozen.DiscardUnknown(m)
}

var xxx_messageInfo_OnCancelFrozen proto.InternalMessageInfo

func (m *OnCancelFrozen) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

type OnFaceLogin struct {
	Degree               int64    `protobuf:"varint,1,opt,name=degree,proto3" json:"degree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnFaceLogin) Reset()         { *m = OnFaceLogin{} }
func (m *OnFaceLogin) String() string { return proto.CompactTextString(m) }
func (*OnFaceLogin) ProtoMessage()    {}
func (*OnFaceLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{13}
}

func (m *OnFaceLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnFaceLogin.Unmarshal(m, b)
}
func (m *OnFaceLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnFaceLogin.Marshal(b, m, deterministic)
}
func (m *OnFaceLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnFaceLogin.Merge(m, src)
}
func (m *OnFaceLogin) XXX_Size() int {
	return xxx_messageInfo_OnFaceLogin.Size(m)
}
func (m *OnFaceLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OnFaceLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OnFaceLogin proto.InternalMessageInfo

func (m *OnFaceLogin) GetDegree() int64 {
	if m != nil {
		return m.Degree
	}
	return 0
}

// 常用设备改变时
type OnCommonEquipmentChanges struct {
	SendMessageToUser    int64    `protobuf:"varint,1,opt,name=sendMessageToUser,proto3" json:"sendMessageToUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCommonEquipmentChanges) Reset()         { *m = OnCommonEquipmentChanges{} }
func (m *OnCommonEquipmentChanges) String() string { return proto.CompactTextString(m) }
func (*OnCommonEquipmentChanges) ProtoMessage()    {}
func (*OnCommonEquipmentChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{14}
}

func (m *OnCommonEquipmentChanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCommonEquipmentChanges.Unmarshal(m, b)
}
func (m *OnCommonEquipmentChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCommonEquipmentChanges.Marshal(b, m, deterministic)
}
func (m *OnCommonEquipmentChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCommonEquipmentChanges.Merge(m, src)
}
func (m *OnCommonEquipmentChanges) XXX_Size() int {
	return xxx_messageInfo_OnCommonEquipmentChanges.Size(m)
}
func (m *OnCommonEquipmentChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCommonEquipmentChanges.DiscardUnknown(m)
}

var xxx_messageInfo_OnCommonEquipmentChanges proto.InternalMessageInfo

func (m *OnCommonEquipmentChanges) GetSendMessageToUser() int64 {
	if m != nil {
		return m.SendMessageToUser
	}
	return 0
}

type OnQRLogin struct {
	RefreshDuration      int64    `protobuf:"varint,1,opt,name=refreshDuration,proto3" json:"refreshDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnQRLogin) Reset()         { *m = OnQRLogin{} }
func (m *OnQRLogin) String() string { return proto.CompactTextString(m) }
func (*OnQRLogin) ProtoMessage()    {}
func (*OnQRLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{15}
}

func (m *OnQRLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnQRLogin.Unmarshal(m, b)
}
func (m *OnQRLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnQRLogin.Marshal(b, m, deterministic)
}
func (m *OnQRLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnQRLogin.Merge(m, src)
}
func (m *OnQRLogin) XXX_Size() int {
	return xxx_messageInfo_OnQRLogin.Size(m)
}
func (m *OnQRLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OnQRLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OnQRLogin proto.InternalMessageInfo

func (m *OnQRLogin) GetRefreshDuration() int64 {
	if m != nil {
		return m.RefreshDuration
	}
	return 0
}

type OnRegister struct {
	OpenReview                   int64                    `protobuf:"varint,1,opt,name=openReview,proto3" json:"openReview,omitempty"`
	Mode                         int64                    `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	OpeningTime                  []*OnRegisterOpeningTime `protobuf:"bytes,3,rep,name=openingTime,proto3" json:"openingTime,omitempty"`
	AnIPRegistrationInterval     int64                    `protobuf:"varint,4,opt,name=anIPRegistrationInterval,proto3" json:"anIPRegistrationInterval,omitempty"`
	AnDeviceRegistrationInterval int64                    `protobuf:"varint,5,opt,name=anDeviceRegistrationInterval,proto3" json:"anDeviceRegistrationInterval,omitempty"`
	Submitlal                    int64                    `protobuf:"varint,6,opt,name=submitlal,proto3" json:"submitlal,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                 `json:"-"`
	XXX_unrecognized             []byte                   `json:"-"`
	XXX_sizecache                int32                    `json:"-"`
}

func (m *OnRegister) Reset()         { *m = OnRegister{} }
func (m *OnRegister) String() string { return proto.CompactTextString(m) }
func (*OnRegister) ProtoMessage()    {}
func (*OnRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{16}
}

func (m *OnRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRegister.Unmarshal(m, b)
}
func (m *OnRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRegister.Marshal(b, m, deterministic)
}
func (m *OnRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRegister.Merge(m, src)
}
func (m *OnRegister) XXX_Size() int {
	return xxx_messageInfo_OnRegister.Size(m)
}
func (m *OnRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRegister.DiscardUnknown(m)
}

var xxx_messageInfo_OnRegister proto.InternalMessageInfo

func (m *OnRegister) GetOpenReview() int64 {
	if m != nil {
		return m.OpenReview
	}
	return 0
}

func (m *OnRegister) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *OnRegister) GetOpeningTime() []*OnRegisterOpeningTime {
	if m != nil {
		return m.OpeningTime
	}
	return nil
}

func (m *OnRegister) GetAnIPRegistrationInterval() int64 {
	if m != nil {
		return m.AnIPRegistrationInterval
	}
	return 0
}

func (m *OnRegister) GetAnDeviceRegistrationInterval() int64 {
	if m != nil {
		return m.AnDeviceRegistrationInterval
	}
	return 0
}

func (m *OnRegister) GetSubmitlal() int64 {
	if m != nil {
		return m.Submitlal
	}
	return 0
}

type OnRegisterOpeningTime struct {
	Begin                int64    `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Every                int64    `protobuf:"varint,3,opt,name=every,proto3" json:"every,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnRegisterOpeningTime) Reset()         { *m = OnRegisterOpeningTime{} }
func (m *OnRegisterOpeningTime) String() string { return proto.CompactTextString(m) }
func (*OnRegisterOpeningTime) ProtoMessage()    {}
func (*OnRegisterOpeningTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{17}
}

func (m *OnRegisterOpeningTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRegisterOpeningTime.Unmarshal(m, b)
}
func (m *OnRegisterOpeningTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRegisterOpeningTime.Marshal(b, m, deterministic)
}
func (m *OnRegisterOpeningTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRegisterOpeningTime.Merge(m, src)
}
func (m *OnRegisterOpeningTime) XXX_Size() int {
	return xxx_messageInfo_OnRegisterOpeningTime.Size(m)
}
func (m *OnRegisterOpeningTime) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRegisterOpeningTime.DiscardUnknown(m)
}

var xxx_messageInfo_OnRegisterOpeningTime proto.InternalMessageInfo

func (m *OnRegisterOpeningTime) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *OnRegisterOpeningTime) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *OnRegisterOpeningTime) GetEvery() int64 {
	if m != nil {
		return m.Every
	}
	return 0
}

type OnLogin struct {
	AllowOtherProjectUserToLogin int64 `protobuf:"varint,1,opt,name=allowOtherProjectUserToLogin,proto3" json:"allowOtherProjectUserToLogin,omitempty"`
	// 1：手机号 2：邮箱 3：手机验证码  4：邮箱验证码
	// 5：第三方账号  6：二维码  7: 游客模式
	Mode                     []int64                     `protobuf:"varint,2,rep,packed,name=mode,proto3" json:"mode,omitempty"`
	Verification             int64                       `protobuf:"varint,3,opt,name=verification,proto3" json:"verification,omitempty"`
	MaxCountOfErrorPassword  []*MaxCountOfErrorPassword  `protobuf:"bytes,4,rep,name=maxCountOfErrorPassword,proto3" json:"maxCountOfErrorPassword,omitempty"`
	MaxCountOfInvalidAccount []*MaxCountOfInvalidAccount `protobuf:"bytes,5,rep,name=maxCountOfInvalidAccount,proto3" json:"maxCountOfInvalidAccount,omitempty"`
	Submitlal                int64                       `protobuf:"varint,6,opt,name=submitlal,proto3" json:"submitlal,omitempty"`
	MaxCountOfOnline         *MaxCountOfOnline           `protobuf:"bytes,7,opt,name=MaxCountOfOnline,proto3" json:"MaxCountOfOnline,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *OnLogin) Reset()         { *m = OnLogin{} }
func (m *OnLogin) String() string { return proto.CompactTextString(m) }
func (*OnLogin) ProtoMessage()    {}
func (*OnLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{18}
}

func (m *OnLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnLogin.Unmarshal(m, b)
}
func (m *OnLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnLogin.Marshal(b, m, deterministic)
}
func (m *OnLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnLogin.Merge(m, src)
}
func (m *OnLogin) XXX_Size() int {
	return xxx_messageInfo_OnLogin.Size(m)
}
func (m *OnLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OnLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OnLogin proto.InternalMessageInfo

func (m *OnLogin) GetAllowOtherProjectUserToLogin() int64 {
	if m != nil {
		return m.AllowOtherProjectUserToLogin
	}
	return 0
}

func (m *OnLogin) GetMode() []int64 {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *OnLogin) GetVerification() int64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

func (m *OnLogin) GetMaxCountOfErrorPassword() []*MaxCountOfErrorPassword {
	if m != nil {
		return m.MaxCountOfErrorPassword
	}
	return nil
}

func (m *OnLogin) GetMaxCountOfInvalidAccount() []*MaxCountOfInvalidAccount {
	if m != nil {
		return m.MaxCountOfInvalidAccount
	}
	return nil
}

func (m *OnLogin) GetSubmitlal() int64 {
	if m != nil {
		return m.Submitlal
	}
	return 0
}

func (m *OnLogin) GetMaxCountOfOnline() *MaxCountOfOnline {
	if m != nil {
		return m.MaxCountOfOnline
	}
	return nil
}

// 既一个用户（IP/Device）在规定的时间内输入多次错误的用户账号，可以怀疑是刷数据等其他操作
type MaxCountOfInvalidAccount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Action               int64    `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,3,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxCountOfInvalidAccount) Reset()         { *m = MaxCountOfInvalidAccount{} }
func (m *MaxCountOfInvalidAccount) String() string { return proto.CompactTextString(m) }
func (*MaxCountOfInvalidAccount) ProtoMessage()    {}
func (*MaxCountOfInvalidAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{19}
}

func (m *MaxCountOfInvalidAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxCountOfInvalidAccount.Unmarshal(m, b)
}
func (m *MaxCountOfInvalidAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxCountOfInvalidAccount.Marshal(b, m, deterministic)
}
func (m *MaxCountOfInvalidAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxCountOfInvalidAccount.Merge(m, src)
}
func (m *MaxCountOfInvalidAccount) XXX_Size() int {
	return xxx_messageInfo_MaxCountOfInvalidAccount.Size(m)
}
func (m *MaxCountOfInvalidAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxCountOfInvalidAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MaxCountOfInvalidAccount proto.InternalMessageInfo

func (m *MaxCountOfInvalidAccount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MaxCountOfInvalidAccount) GetAction() int64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *MaxCountOfInvalidAccount) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

type MaxCountOfErrorPassword struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Action               int64    `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,3,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxCountOfErrorPassword) Reset()         { *m = MaxCountOfErrorPassword{} }
func (m *MaxCountOfErrorPassword) String() string { return proto.CompactTextString(m) }
func (*MaxCountOfErrorPassword) ProtoMessage()    {}
func (*MaxCountOfErrorPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{20}
}

func (m *MaxCountOfErrorPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxCountOfErrorPassword.Unmarshal(m, b)
}
func (m *MaxCountOfErrorPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxCountOfErrorPassword.Marshal(b, m, deterministic)
}
func (m *MaxCountOfErrorPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxCountOfErrorPassword.Merge(m, src)
}
func (m *MaxCountOfErrorPassword) XXX_Size() int {
	return xxx_messageInfo_MaxCountOfErrorPassword.Size(m)
}
func (m *MaxCountOfErrorPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxCountOfErrorPassword.DiscardUnknown(m)
}

var xxx_messageInfo_MaxCountOfErrorPassword proto.InternalMessageInfo

func (m *MaxCountOfErrorPassword) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MaxCountOfErrorPassword) GetAction() int64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *MaxCountOfErrorPassword) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

type MaxCountOfOnline struct {
	Android              int64    `protobuf:"varint,1,opt,name=android,proto3" json:"android,omitempty"`
	Windows              int64    `protobuf:"varint,2,opt,name=windows,proto3" json:"windows,omitempty"`
	MacOS                int64    `protobuf:"varint,3,opt,name=macOS,proto3" json:"macOS,omitempty"`
	Web                  int64    `protobuf:"varint,4,opt,name=web,proto3" json:"web,omitempty"`
	IOS                  int64    `protobuf:"varint,5,opt,name=iOS,proto3" json:"iOS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxCountOfOnline) Reset()         { *m = MaxCountOfOnline{} }
func (m *MaxCountOfOnline) String() string { return proto.CompactTextString(m) }
func (*MaxCountOfOnline) ProtoMessage()    {}
func (*MaxCountOfOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{21}
}

func (m *MaxCountOfOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxCountOfOnline.Unmarshal(m, b)
}
func (m *MaxCountOfOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxCountOfOnline.Marshal(b, m, deterministic)
}
func (m *MaxCountOfOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxCountOfOnline.Merge(m, src)
}
func (m *MaxCountOfOnline) XXX_Size() int {
	return xxx_messageInfo_MaxCountOfOnline.Size(m)
}
func (m *MaxCountOfOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxCountOfOnline.DiscardUnknown(m)
}

var xxx_messageInfo_MaxCountOfOnline proto.InternalMessageInfo

func (m *MaxCountOfOnline) GetAndroid() int64 {
	if m != nil {
		return m.Android
	}
	return 0
}

func (m *MaxCountOfOnline) GetWindows() int64 {
	if m != nil {
		return m.Windows
	}
	return 0
}

func (m *MaxCountOfOnline) GetMacOS() int64 {
	if m != nil {
		return m.MacOS
	}
	return 0
}

func (m *MaxCountOfOnline) GetWeb() int64 {
	if m != nil {
		return m.Web
	}
	return 0
}

func (m *MaxCountOfOnline) GetIOS() int64 {
	if m != nil {
		return m.IOS
	}
	return 0
}

type OnVerification struct {
	CombinationMode      int64    `protobuf:"varint,1,opt,name=combinationMode,proto3" json:"combinationMode,omitempty"`
	EffectiveTime        int64    `protobuf:"varint,2,opt,name=effectiveTime,proto3" json:"effectiveTime,omitempty"`
	VoucherDuration      int64    `protobuf:"varint,3,opt,name=voucherDuration,proto3" json:"voucherDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnVerification) Reset()         { *m = OnVerification{} }
func (m *OnVerification) String() string { return proto.CompactTextString(m) }
func (*OnVerification) ProtoMessage()    {}
func (*OnVerification) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b63c1749c2ca181, []int{22}
}

func (m *OnVerification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnVerification.Unmarshal(m, b)
}
func (m *OnVerification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnVerification.Marshal(b, m, deterministic)
}
func (m *OnVerification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnVerification.Merge(m, src)
}
func (m *OnVerification) XXX_Size() int {
	return xxx_messageInfo_OnVerification.Size(m)
}
func (m *OnVerification) XXX_DiscardUnknown() {
	xxx_messageInfo_OnVerification.DiscardUnknown(m)
}

var xxx_messageInfo_OnVerification proto.InternalMessageInfo

func (m *OnVerification) GetCombinationMode() int64 {
	if m != nil {
		return m.CombinationMode
	}
	return 0
}

func (m *OnVerification) GetEffectiveTime() int64 {
	if m != nil {
		return m.EffectiveTime
	}
	return 0
}

func (m *OnVerification) GetVoucherDuration() int64 {
	if m != nil {
		return m.VoucherDuration
	}
	return 0
}

func init() {
	proto.RegisterType((*ProjectStrategy)(nil), "fs.base.ProjectStrategy")
	proto.RegisterType((*Configuration)(nil), "fs.base.Configuration")
	proto.RegisterType((*Events)(nil), "fs.base.Events")
	proto.RegisterType((*OnInviteUser)(nil), "fs.base.OnInviteUser")
	proto.RegisterType((*OnSubmitReview)(nil), "fs.base.OnSubmitReview")
	proto.RegisterType((*OnElsewhereLogin)(nil), "fs.base.OnElsewhereLogin")
	proto.RegisterType((*OnResetPassword)(nil), "fs.base.OnResetPassword")
	proto.RegisterType((*OnChangePhoneNumber)(nil), "fs.base.OnChangePhoneNumber")
	proto.RegisterType((*OnChangeEmail)(nil), "fs.base.OnChangeEmail")
	proto.RegisterType((*OnChangeOAuth)(nil), "fs.base.OnChangeOAuth")
	proto.RegisterType((*OnChangeFace)(nil), "fs.base.OnChangeFace")
	proto.RegisterType((*OnRequestFrozen)(nil), "fs.base.OnRequestFrozen")
	proto.RegisterType((*OnCancelFrozen)(nil), "fs.base.OnCancelFrozen")
	proto.RegisterType((*OnFaceLogin)(nil), "fs.base.OnFaceLogin")
	proto.RegisterType((*OnCommonEquipmentChanges)(nil), "fs.base.OnCommonEquipmentChanges")
	proto.RegisterType((*OnQRLogin)(nil), "fs.base.OnQRLogin")
	proto.RegisterType((*OnRegister)(nil), "fs.base.OnRegister")
	proto.RegisterType((*OnRegisterOpeningTime)(nil), "fs.base.OnRegisterOpeningTime")
	proto.RegisterType((*OnLogin)(nil), "fs.base.OnLogin")
	proto.RegisterType((*MaxCountOfInvalidAccount)(nil), "fs.base.MaxCountOfInvalidAccount")
	proto.RegisterType((*MaxCountOfErrorPassword)(nil), "fs.base.MaxCountOfErrorPassword")
	proto.RegisterType((*MaxCountOfOnline)(nil), "fs.base.MaxCountOfOnline")
	proto.RegisterType((*OnVerification)(nil), "fs.base.OnVerification")
}

func init() { proto.RegisterFile("base/pb/strategy1.proto", fileDescriptor_6b63c1749c2ca181) }

var fileDescriptor_6b63c1749c2ca181 = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0x96, 0xe3, 0xc4, 0x69, 0x8e, 0x93, 0xda, 0xef, 0xf4, 0x23, 0xdb, 0x57, 0x55, 0xe5, 0xae,
	0x40, 0x58, 0x15, 0x4a, 0x21, 0x05, 0xa4, 0x22, 0x10, 0xa4, 0xa9, 0x2b, 0x2c, 0xd1, 0x3a, 0x4c,
	0x1a, 0x90, 0x90, 0x40, 0x5a, 0xef, 0x1e, 0xdb, 0x53, 0x79, 0x67, 0xdc, 0xd9, 0xb5, 0xdd, 0x70,
	0x85, 0xb8, 0xe0, 0x82, 0x5f, 0xc1, 0x0d, 0xff, 0x13, 0xcd, 0xc7, 0xae, 0x67, 0xd7, 0xeb, 0x28,
	0x95, 0xb8, 0xdb, 0x73, 0x9e, 0xe7, 0x9c, 0x3d, 0x7b, 0xbe, 0x66, 0x16, 0x0e, 0x87, 0x41, 0x82,
	0x8f, 0x67, 0xc3, 0xc7, 0x49, 0x2a, 0x83, 0x14, 0xc7, 0x97, 0x9f, 0x1e, 0xcd, 0xa4, 0x48, 0x05,
	0xd9, 0x1d, 0x25, 0x47, 0x0a, 0xf3, 0xff, 0xd8, 0x82, 0xd6, 0x99, 0x14, 0x6f, 0x30, 0x4c, 0xcf,
	0x2d, 0x87, 0xdc, 0x87, 0xbd, 0x99, 0x51, 0xf5, 0x23, 0xaf, 0xd6, 0xa9, 0x75, 0xf7, 0xe8, 0x4a,
	0x41, 0x3c, 0xd8, 0x0d, 0x25, 0x06, 0xa9, 0x90, 0xde, 0x96, 0xc6, 0x32, 0x91, 0xfc, 0x1f, 0x6e,
	0xe8, 0x47, 0x3c, 0x49, 0xbd, 0x7a, 0xa7, 0xd6, 0xad, 0xd3, 0x5c, 0x56, 0x58, 0x2c, 0x22, 0x36,
	0xba, 0x3c, 0x49, 0xbd, 0x6d, 0x83, 0x65, 0xb2, 0xf2, 0xb8, 0x40, 0x99, 0x30, 0xc1, 0xbd, 0x1d,
	0x0d, 0x65, 0x22, 0xf9, 0x08, 0x1a, 0xb8, 0x40, 0x9e, 0x26, 0x5e, 0xa3, 0x53, 0xeb, 0x36, 0x8f,
	0x5b, 0x47, 0x36, 0xee, 0xa3, 0x9e, 0x56, 0x53, 0x0b, 0x93, 0xaf, 0xe0, 0x20, 0x14, 0x7c, 0xc4,
	0xc6, 0x73, 0x19, 0xa4, 0xca, 0xd1, 0xae, 0xe6, 0xdf, 0xcd, 0xf9, 0xa7, 0x2e, 0x4a, 0x8b, 0x64,
	0xff, 0x27, 0x38, 0x28, 0xe0, 0xe4, 0x11, 0xb4, 0x25, 0x8e, 0x59, 0x92, 0xa2, 0xa4, 0xb8, 0x60,
	0xb8, 0xcc, 0x13, 0xb1, 0xa6, 0x57, 0x5f, 0x26, 0x66, 0xc8, 0x5f, 0xb3, 0x18, 0x6d, 0x42, 0x72,
	0xd9, 0xff, 0xf3, 0x06, 0x34, 0x4c, 0xa4, 0xe4, 0x09, 0x80, 0xe0, 0xd4, 0x1a, 0x6b, 0x67, 0xcd,
	0xe3, 0x5b, 0x79, 0x78, 0x83, 0x1c, 0xa2, 0x0e, 0x8d, 0x3c, 0x82, 0x5d, 0xc1, 0xbf, 0x17, 0x63,
	0xc6, 0xb5, 0xeb, 0xe6, 0x71, 0xdb, 0xb1, 0xd0, 0x7a, 0x9a, 0x11, 0xc8, 0x37, 0x70, 0x53, 0xf0,
	0x1f, 0x51, 0xb2, 0x11, 0x0b, 0x4d, 0x0e, 0xea, 0xda, 0xe4, 0xd0, 0x31, 0x71, 0x61, 0x5a, 0xa2,
	0x93, 0x4f, 0x60, 0x4f, 0xf0, 0x1f, 0xa8, 0x79, 0xdd, 0xb6, 0xb6, 0x25, 0x8e, 0xad, 0x45, 0xe8,
	0x8a, 0x44, 0xbe, 0x80, 0xa6, 0xe0, 0x2f, 0x82, 0x10, 0x8d, 0xcd, 0x8e, 0xb6, 0xb9, 0xed, 0xd8,
	0xe4, 0x18, 0x75, 0x89, 0xe4, 0x17, 0xf0, 0x06, 0xfc, 0x54, 0xc4, 0xb1, 0xe0, 0xbd, 0xb7, 0x73,
	0x36, 0x8b, 0x91, 0xa7, 0xa7, 0x93, 0x80, 0x8f, 0x31, 0x2b, 0xf4, 0x43, 0xc7, 0x49, 0x35, 0x91,
	0x6e, 0x74, 0x41, 0x9e, 0x41, 0x4b, 0xe5, 0xf0, 0xed, 0x1c, 0x93, 0xf4, 0x85, 0x14, 0xbf, 0x61,
	0xd6, 0x0e, 0x5e, 0x21, 0xdf, 0x0e, 0x4e, 0xcb, 0x06, 0x26, 0x9b, 0xa7, 0x01, 0x0f, 0x71, 0x6a,
	0x5d, 0xdc, 0x58, 0xcb, 0xa6, 0x0b, 0xd3, 0x12, 0x9d, 0xbc, 0x82, 0x5b, 0x82, 0x9b, 0x88, 0xce,
	0x26, 0x82, 0xe3, 0xab, 0x79, 0x3c, 0x44, 0xe9, 0xed, 0x69, 0x2f, 0xf7, 0x5d, 0x2f, 0x65, 0x0e,
	0xad, 0x32, 0x54, 0x1d, 0x9e, 0xa9, 0x7b, 0x71, 0xc0, 0xa6, 0x1e, 0x94, 0x3a, 0x7c, 0xe0, 0xa2,
	0xb4, 0x48, 0x76, 0xad, 0x07, 0x27, 0xf3, 0x74, 0xe2, 0x35, 0x37, 0x58, 0x6b, 0x94, 0x16, 0xc9,
	0xe4, 0x29, 0xec, 0x67, 0x0a, 0x55, 0x44, 0x6f, 0x5f, 0x1b, 0xdf, 0x59, 0x33, 0x56, 0x20, 0x2d,
	0x50, 0xb3, 0x5a, 0x24, 0x98, 0x9e, 0x05, 0x49, 0xb2, 0x14, 0x32, 0xf2, 0x0e, 0x2a, 0x6a, 0xe1,
	0xe0, 0xb4, 0x6c, 0x40, 0x7a, 0xd0, 0x16, 0xbc, 0x37, 0x4d, 0x70, 0x39, 0x41, 0x69, 0x7b, 0xed,
	0xa6, 0x76, 0x72, 0xcf, 0x71, 0x52, 0x24, 0xd0, 0x35, 0x13, 0x53, 0xd2, 0xf3, 0xf9, 0x30, 0x66,
	0xa9, 0x19, 0x5e, 0xaf, 0xb5, 0x56, 0x52, 0x17, 0xa6, 0x25, 0xba, 0x49, 0x43, 0x9f, 0x2f, 0x58,
	0x8a, 0x17, 0x09, 0x4a, 0xaf, 0xbd, 0x96, 0x86, 0x15, 0x48, 0x0b, 0x54, 0xff, 0x05, 0xec, 0xbb,
	0x28, 0x79, 0x00, 0x80, 0xef, 0x66, 0x4c, 0xa2, 0x5e, 0x1b, 0x35, 0xbd, 0xf5, 0x1c, 0x0d, 0xb9,
	0x0b, 0x0d, 0x69, 0x62, 0xdc, 0xd2, 0x98, 0x95, 0xfc, 0x5f, 0xe1, 0x66, 0x31, 0x48, 0xe2, 0xc3,
	0xbe, 0xc4, 0x99, 0x90, 0xa9, 0xf2, 0x9b, 0xaf, 0xa9, 0x82, 0x8e, 0x74, 0xa1, 0x25, 0x31, 0x99,
	0x09, 0x9e, 0xe0, 0x4b, 0x4c, 0x92, 0x60, 0x9c, 0x6d, 0xaa, 0xb2, 0xda, 0x8f, 0xa0, 0x5d, 0xce,
	0x24, 0xf9, 0x18, 0xfe, 0x97, 0x20, 0x8f, 0x2c, 0xe5, 0xb5, 0xd0, 0xdf, 0x6e, 0x42, 0x5e, 0x07,
	0x54, 0x3c, 0x0b, 0x77, 0x09, 0x99, 0xf8, 0x0b, 0x3a, 0xff, 0x6b, 0x68, 0x95, 0x8a, 0x4e, 0x6e,
	0xc3, 0xce, 0x4c, 0x75, 0xbb, 0x75, 0x6c, 0x04, 0xa5, 0x45, 0xdd, 0xec, 0xc6, 0x8b, 0x11, 0xfc,
	0xa7, 0x70, 0xab, 0x62, 0x6c, 0xd6, 0xde, 0x5c, 0xab, 0x78, 0xf3, 0x13, 0x38, 0x28, 0xcc, 0xc9,
	0xfb, 0x1a, 0x99, 0x79, 0xb8, 0x8e, 0xd1, 0xb1, 0xaa, 0xb8, 0x33, 0x08, 0xd7, 0xb1, 0xb9, 0x30,
	0x79, 0x71, 0xf7, 0xd0, 0x35, 0xcc, 0x54, 0x33, 0x25, 0xba, 0x25, 0xfa, 0x7c, 0x24, 0x6c, 0xaa,
	0x1c, 0x8d, 0xff, 0x99, 0x6a, 0x9a, 0xc2, 0x72, 0xba, 0x4e, 0x30, 0x1f, 0x42, 0xd3, 0x59, 0xe0,
	0xaa, 0x23, 0x23, 0x1c, 0x4b, 0xcc, 0x2a, 0x64, 0x25, 0xff, 0xbb, 0xcd, 0xbb, 0xfc, 0xfd, 0x3a,
	0xc7, 0xff, 0x1c, 0xf6, 0xf2, 0x53, 0xc6, 0xb4, 0xec, 0x48, 0x62, 0x32, 0x79, 0x9e, 0x1d, 0xe9,
	0xc6, 0xb0, 0xac, 0xf6, 0xff, 0xde, 0x02, 0x58, 0x1d, 0x9f, 0x2a, 0x19, 0xea, 0xf8, 0xb5, 0x13,
	0x6e, 0x27, 0x6b, 0xa5, 0x21, 0x04, 0xb6, 0x63, 0x11, 0xa1, 0x4d, 0x93, 0x7e, 0x26, 0xdf, 0x42,
	0x53, 0x31, 0x18, 0x1f, 0xeb, 0x71, 0xac, 0x77, 0xea, 0xdd, 0xe6, 0xf1, 0x83, 0x8a, 0xc3, 0x79,
	0xb0, 0x62, 0x51, 0xd7, 0x84, 0x7c, 0x09, 0x5e, 0xc0, 0xfb, 0x67, 0x86, 0x67, 0x02, 0xeb, 0xf3,
	0x14, 0xe5, 0x22, 0x98, 0xda, 0xeb, 0xce, 0x46, 0x9c, 0x3c, 0x83, 0xfb, 0x01, 0x7f, 0x8e, 0x0b,
	0x16, 0x62, 0xa5, 0xbd, 0xb9, 0x13, 0x5d, 0xc9, 0x51, 0x57, 0x36, 0x53, 0xf0, 0x69, 0x30, 0xd5,
	0x47, 0x68, 0x9d, 0xae, 0x14, 0xfe, 0x05, 0xdc, 0xa9, 0xfc, 0x06, 0x35, 0x5f, 0x43, 0x54, 0xeb,
	0xd4, 0x4e, 0x9d, 0x16, 0x48, 0x1b, 0xea, 0xc8, 0x23, 0x9b, 0x21, 0xf5, 0xa8, 0xe7, 0x70, 0x81,
	0xf2, 0xd2, 0x5e, 0xeb, 0x8c, 0xe0, 0xff, 0x53, 0x87, 0x5d, 0x7b, 0x0d, 0xd1, 0x1f, 0x31, 0x9d,
	0x8a, 0xe5, 0x20, 0x9d, 0xa0, 0xb4, 0x17, 0x4a, 0x55, 0xd5, 0xd7, 0xc2, 0xec, 0xeb, 0x9a, 0xfd,
	0x88, 0x2b, 0x38, 0x4e, 0x69, 0xea, 0x79, 0x69, 0xca, 0x9d, 0x5a, 0xaf, 0xe8, 0xff, 0x9f, 0xe1,
	0x30, 0x0e, 0xde, 0x9d, 0x8a, 0x39, 0x4f, 0x07, 0xa3, 0x9e, 0x94, 0x42, 0xe6, 0x67, 0xcd, 0xb6,
	0x2e, 0x65, 0x27, 0x2f, 0xe5, 0xcb, 0x6a, 0x1e, 0xdd, 0xe4, 0x40, 0x5d, 0x55, 0x56, 0x50, 0x9f,
	0x2f, 0x82, 0x29, 0x8b, 0x4e, 0xc2, 0x50, 0xc9, 0xde, 0x8e, 0x76, 0xfe, 0xb0, 0xc2, 0x79, 0x91,
	0x48, 0x37, 0xba, 0xb8, 0xba, 0x6e, 0xea, 0xe0, 0x5b, 0xf9, 0x1c, 0xf0, 0x29, 0xe3, 0x68, 0x6f,
	0x32, 0xf7, 0x2a, 0x5e, 0x6a, 0x08, 0x74, 0xcd, 0xc4, 0x7f, 0x03, 0xde, 0xa6, 0xd0, 0x54, 0x65,
	0xcd, 0xc7, 0xd8, 0x0e, 0x30, 0xda, 0xbb, 0xd0, 0x08, 0x42, 0x67, 0x7d, 0x5b, 0x89, 0x74, 0xa0,
	0x69, 0x0e, 0xa9, 0xc8, 0x0e, 0x8a, 0x02, 0x5d, 0x95, 0xcf, 0xe0, 0x70, 0x43, 0x8e, 0xff, 0xf3,
	0x57, 0xfd, 0x5e, 0x5b, 0x4f, 0x8f, 0xfa, 0x97, 0x08, 0x78, 0x24, 0x05, 0x8b, 0xec, 0x6b, 0x32,
	0x51, 0x21, 0x4b, 0xc6, 0x23, 0xb1, 0x4c, 0xec, 0x9b, 0x32, 0x51, 0x05, 0x16, 0x07, 0xe1, 0xe0,
	0x3c, 0xeb, 0x6e, 0x2d, 0xa8, 0x29, 0x58, 0xe2, 0xd0, 0x4e, 0xaf, 0x7a, 0x54, 0x1a, 0x36, 0x38,
	0xb7, 0xf3, 0xa8, 0x1e, 0xfd, 0xbf, 0x6a, 0x6a, 0xb5, 0x16, 0x6e, 0xd1, 0x5d, 0x68, 0x85, 0x22,
	0x1e, 0x32, 0xae, 0xc5, 0x97, 0xaa, 0x9f, 0xed, 0xe2, 0x2a, 0xa9, 0xc9, 0x07, 0x70, 0x80, 0xa3,
	0x11, 0x86, 0x29, 0x5b, 0x60, 0xfe, 0xf7, 0x50, 0xa7, 0x45, 0xa5, 0xf2, 0xb7, 0x10, 0xf3, 0x70,
	0x82, 0x32, 0x5f, 0x84, 0x26, 0xcc, 0xb2, 0x7a, 0xd8, 0xd0, 0xbf, 0x76, 0x4f, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x77, 0xcf, 0x09, 0xdc, 0xf5, 0x0d, 0x00, 0x00,
}
