// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry/login/pb/login.proto

package fs_entry_login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryByQRCodeRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryByQRCodeRequest) Reset()         { *m = EntryByQRCodeRequest{} }
func (m *EntryByQRCodeRequest) String() string { return proto.CompactTextString(m) }
func (*EntryByQRCodeRequest) ProtoMessage()    {}
func (*EntryByQRCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2a3c537b1fd5462, []int{0}
}

func (m *EntryByQRCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryByQRCodeRequest.Unmarshal(m, b)
}
func (m *EntryByQRCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryByQRCodeRequest.Marshal(b, m, deterministic)
}
func (m *EntryByQRCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryByQRCodeRequest.Merge(m, src)
}
func (m *EntryByQRCodeRequest) XXX_Size() int {
	return xxx_messageInfo_EntryByQRCodeRequest.Size(m)
}
func (m *EntryByQRCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryByQRCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryByQRCodeRequest proto.InternalMessageInfo

func (m *EntryByQRCodeRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type EntryByValidateCodeRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryByValidateCodeRequest) Reset()         { *m = EntryByValidateCodeRequest{} }
func (m *EntryByValidateCodeRequest) String() string { return proto.CompactTextString(m) }
func (*EntryByValidateCodeRequest) ProtoMessage()    {}
func (*EntryByValidateCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2a3c537b1fd5462, []int{1}
}

func (m *EntryByValidateCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryByValidateCodeRequest.Unmarshal(m, b)
}
func (m *EntryByValidateCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryByValidateCodeRequest.Marshal(b, m, deterministic)
}
func (m *EntryByValidateCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryByValidateCodeRequest.Merge(m, src)
}
func (m *EntryByValidateCodeRequest) XXX_Size() int {
	return xxx_messageInfo_EntryByValidateCodeRequest.Size(m)
}
func (m *EntryByValidateCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryByValidateCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryByValidateCodeRequest proto.InternalMessageInfo

func (m *EntryByValidateCodeRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *EntryByValidateCodeRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type EntryByOAuthRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OpenId               string   `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryByOAuthRequest) Reset()         { *m = EntryByOAuthRequest{} }
func (m *EntryByOAuthRequest) String() string { return proto.CompactTextString(m) }
func (*EntryByOAuthRequest) ProtoMessage()    {}
func (*EntryByOAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2a3c537b1fd5462, []int{2}
}

func (m *EntryByOAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryByOAuthRequest.Unmarshal(m, b)
}
func (m *EntryByOAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryByOAuthRequest.Marshal(b, m, deterministic)
}
func (m *EntryByOAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryByOAuthRequest.Merge(m, src)
}
func (m *EntryByOAuthRequest) XXX_Size() int {
	return xxx_messageInfo_EntryByOAuthRequest.Size(m)
}
func (m *EntryByOAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryByOAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryByOAuthRequest proto.InternalMessageInfo

func (m *EntryByOAuthRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *EntryByOAuthRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EntryByOAuthRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *EntryByOAuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EntryByAPRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryByAPRequest) Reset()         { *m = EntryByAPRequest{} }
func (m *EntryByAPRequest) String() string { return proto.CompactTextString(m) }
func (*EntryByAPRequest) ProtoMessage()    {}
func (*EntryByAPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2a3c537b1fd5462, []int{3}
}

func (m *EntryByAPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryByAPRequest.Unmarshal(m, b)
}
func (m *EntryByAPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryByAPRequest.Marshal(b, m, deterministic)
}
func (m *EntryByAPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryByAPRequest.Merge(m, src)
}
func (m *EntryByAPRequest) XXX_Size() int {
	return xxx_messageInfo_EntryByAPRequest.Size(m)
}
func (m *EntryByAPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryByAPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryByAPRequest proto.InternalMessageInfo

func (m *EntryByAPRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *EntryByAPRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EntryByAPRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*EntryByQRCodeRequest)(nil), "fs.entry.login.EntryByQRCodeRequest")
	proto.RegisterType((*EntryByValidateCodeRequest)(nil), "fs.entry.login.EntryByValidateCodeRequest")
	proto.RegisterType((*EntryByOAuthRequest)(nil), "fs.entry.login.EntryByOAuthRequest")
	proto.RegisterType((*EntryByAPRequest)(nil), "fs.entry.login.EntryByAPRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	// 使用密码账号登录(手机，邮箱，企业号)
	EntryByAP(ctx context.Context, in *EntryByAPRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 使用第三方登录
	EntryByOAuth(ctx context.Context, in *EntryByOAuthRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 使用验证码登录(手机，邮箱)
	EntryByValidateCode(ctx context.Context, in *EntryByValidateCodeRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 使用二维码登录(有平台限制)
	EntryByQRCode(ctx context.Context, in *EntryByQRCodeRequest, opts ...grpc.CallOption) (*pb.Response, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) EntryByAP(ctx context.Context, in *EntryByAPRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.entry.login.Login/EntryByAP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) EntryByOAuth(ctx context.Context, in *EntryByOAuthRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.entry.login.Login/EntryByOAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) EntryByValidateCode(ctx context.Context, in *EntryByValidateCodeRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.entry.login.Login/EntryByValidateCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) EntryByQRCode(ctx context.Context, in *EntryByQRCodeRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.entry.login.Login/EntryByQRCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	// 使用密码账号登录(手机，邮箱，企业号)
	EntryByAP(context.Context, *EntryByAPRequest) (*pb.Response, error)
	// 使用第三方登录
	EntryByOAuth(context.Context, *EntryByOAuthRequest) (*pb.Response, error)
	// 使用验证码登录(手机，邮箱)
	EntryByValidateCode(context.Context, *EntryByValidateCodeRequest) (*pb.Response, error)
	// 使用二维码登录(有平台限制)
	EntryByQRCode(context.Context, *EntryByQRCodeRequest) (*pb.Response, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_EntryByAP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryByAPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).EntryByAP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.entry.login.Login/EntryByAP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).EntryByAP(ctx, req.(*EntryByAPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_EntryByOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryByOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).EntryByOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.entry.login.Login/EntryByOAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).EntryByOAuth(ctx, req.(*EntryByOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_EntryByValidateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryByValidateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).EntryByValidateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.entry.login.Login/EntryByValidateCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).EntryByValidateCode(ctx, req.(*EntryByValidateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_EntryByQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryByQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).EntryByQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.entry.login.Login/EntryByQRCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).EntryByQRCode(ctx, req.(*EntryByQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.entry.login.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntryByAP",
			Handler:    _Login_EntryByAP_Handler,
		},
		{
			MethodName: "EntryByOAuth",
			Handler:    _Login_EntryByOAuth_Handler,
		},
		{
			MethodName: "EntryByValidateCode",
			Handler:    _Login_EntryByValidateCode_Handler,
		},
		{
			MethodName: "EntryByQRCode",
			Handler:    _Login_EntryByQRCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entry/login/pb/login.proto",
}

func init() { proto.RegisterFile("entry/login/pb/login.proto", fileDescriptor_f2a3c537b1fd5462) }

var fileDescriptor_f2a3c537b1fd5462 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4f, 0xea, 0x40,
	0x10, 0xc6, 0x03, 0x0f, 0x78, 0x8f, 0x79, 0x62, 0x74, 0x25, 0xa6, 0xe9, 0x09, 0xab, 0x07, 0xa2,
	0xc9, 0x36, 0xc1, 0x93, 0x37, 0xd1, 0x68, 0x34, 0xd1, 0xa8, 0x8d, 0x7a, 0x5f, 0xe8, 0x20, 0xa4,
	0xb0, 0xb3, 0x76, 0xb7, 0x31, 0xf0, 0x5f, 0xf9, 0x1f, 0x9a, 0x6e, 0x4b, 0x03, 0xa6, 0x1c, 0x38,
	0xed, 0x7e, 0xbb, 0xf9, 0x7e, 0xdf, 0x64, 0x66, 0xc0, 0x45, 0x69, 0xe2, 0xb9, 0x3f, 0xa5, 0x8f,
	0x89, 0xf4, 0xd5, 0x20, 0xbb, 0x70, 0x15, 0x93, 0x21, 0xb6, 0x3b, 0xd2, 0xdc, 0x7e, 0x73, 0xfb,
	0xea, 0x9e, 0x2d, 0x74, 0xa4, 0x44, 0x1c, 0x61, 0xcc, 0x87, 0x34, 0xf3, 0x47, 0x94, 0xc8, 0x50,
	0x98, 0x09, 0x49, 0x7f, 0x20, 0x34, 0xa6, 0xee, 0xf4, 0xcc, 0xcc, 0xde, 0x05, 0xb4, 0x6f, 0x52,
	0xef, 0xd5, 0xfc, 0x25, 0xb8, 0xa6, 0x10, 0x03, 0xfc, 0x4c, 0x50, 0x1b, 0x76, 0x04, 0xb5, 0x19,
	0x1a, 0xe1, 0x54, 0x3a, 0x95, 0xee, 0xff, 0x5e, 0x8b, 0x8f, 0x34, 0xb7, 0xae, 0x47, 0x34, 0x22,
	0xb0, 0x5f, 0xde, 0x1b, 0xb8, 0xb9, 0xf5, 0x5d, 0x4c, 0x27, 0xa1, 0x30, 0xb8, 0x1d, 0x80, 0xb5,
	0xa1, 0xae, 0xc6, 0x24, 0xd1, 0xa9, 0x76, 0x2a, 0xdd, 0x66, 0x90, 0x09, 0x6f, 0x01, 0x07, 0x39,
	0xf6, 0xa9, 0x9f, 0x98, 0xf1, 0x16, 0x3c, 0x06, 0x35, 0x33, 0x57, 0x4b, 0x9c, 0xbd, 0xb3, 0x43,
	0x68, 0x90, 0x42, 0x79, 0x1f, 0x3a, 0x7f, 0xec, 0x6b, 0xae, 0xd2, 0x6c, 0x43, 0x11, 0x4a, 0xa7,
	0x96, 0x65, 0x5b, 0xe1, 0x45, 0xb0, 0x97, 0x67, 0xf7, 0x9f, 0xb7, 0x08, 0x76, 0xe0, 0xaf, 0x18,
	0x0e, 0x29, 0x91, 0x26, 0xcf, 0x5e, 0x4a, 0xe6, 0xc2, 0x3f, 0x25, 0xb4, 0xfe, 0xa2, 0x78, 0x59,
	0x40, 0xa1, 0x7b, 0xdf, 0x55, 0xa8, 0x3f, 0xa4, 0x13, 0x63, 0x97, 0xd0, 0x2c, 0x62, 0x59, 0x87,
	0xaf, 0xcf, 0x93, 0xff, 0xae, 0xc8, 0xdd, 0x2f, 0x6a, 0x08, 0x50, 0x2b, 0x92, 0x1a, 0xd9, 0x2d,
	0xec, 0xac, 0x36, 0x8d, 0x1d, 0x6f, 0x80, 0xac, 0xb6, 0xb4, 0x8c, 0xf3, 0x5a, 0x34, 0x7f, 0x75,
	0xa6, 0xec, 0x74, 0x03, 0xae, 0x64, 0xf0, 0x65, 0xd4, 0x3b, 0x68, 0xad, 0x2d, 0x19, 0x3b, 0xd9,
	0xc0, 0x5b, 0xdb, 0xc1, 0x12, 0xd2, 0xa0, 0x61, 0xb7, 0xf6, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x30, 0x24, 0x3c, 0x10, 0x03, 0x00, 0x00,
}
