// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safety/verification/pb/verification.proto

package fs_safety_verification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewRequest struct {
	Func                 string   `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	FuncId               int64    `protobuf:"varint,2,opt,name=funcId,proto3" json:"funcId,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRequest) Reset()         { *m = NewRequest{} }
func (m *NewRequest) String() string { return proto.CompactTextString(m) }
func (*NewRequest) ProtoMessage()    {}
func (*NewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c47f403cbdc6a6e0, []int{0}
}

func (m *NewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRequest.Unmarshal(m, b)
}
func (m *NewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRequest.Marshal(b, m, deterministic)
}
func (m *NewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRequest.Merge(m, src)
}
func (m *NewRequest) XXX_Size() int {
	return xxx_messageInfo_NewRequest.Size(m)
}
func (m *NewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRequest proto.InternalMessageInfo

func (m *NewRequest) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *NewRequest) GetFuncId() int64 {
	if m != nil {
		return m.FuncId
	}
	return 0
}

func (m *NewRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type NewResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	VerId                string    `protobuf:"bytes,2,opt,name=verId,proto3" json:"verId,omitempty"`
	Mode                 string    `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewResponse) Reset()         { *m = NewResponse{} }
func (m *NewResponse) String() string { return proto.CompactTextString(m) }
func (*NewResponse) ProtoMessage()    {}
func (*NewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c47f403cbdc6a6e0, []int{1}
}

func (m *NewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponse.Unmarshal(m, b)
}
func (m *NewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponse.Marshal(b, m, deterministic)
}
func (m *NewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponse.Merge(m, src)
}
func (m *NewResponse) XXX_Size() int {
	return xxx_messageInfo_NewResponse.Size(m)
}
func (m *NewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponse proto.InternalMessageInfo

func (m *NewResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *NewResponse) GetVerId() string {
	if m != nil {
		return m.VerId
	}
	return ""
}

func (m *NewResponse) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func init() {
	proto.RegisterType((*NewRequest)(nil), "fs.safety.verification.NewRequest")
	proto.RegisterType((*NewResponse)(nil), "fs.safety.verification.NewResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerificationClient is the client API for Verification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerificationClient interface {
	// 新建验证
	New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewResponse, error)
}

type verificationClient struct {
	cc *grpc.ClientConn
}

func NewVerificationClient(cc *grpc.ClientConn) VerificationClient {
	return &verificationClient{cc}
}

func (c *verificationClient) New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewResponse, error) {
	out := new(NewResponse)
	err := c.cc.Invoke(ctx, "/fs.safety.verification.Verification/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationServer is the server API for Verification service.
type VerificationServer interface {
	// 新建验证
	New(context.Context, *NewRequest) (*NewResponse, error)
}

func RegisterVerificationServer(s *grpc.Server, srv VerificationServer) {
	s.RegisterService(&_Verification_serviceDesc, srv)
}

func _Verification_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.safety.verification.Verification/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServer).New(ctx, req.(*NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Verification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.safety.verification.Verification",
	HandlerType: (*VerificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Verification_New_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "safety/verification/pb/verification.proto",
}

func init() {
	proto.RegisterFile("safety/verification/pb/verification.proto", fileDescriptor_c47f403cbdc6a6e0)
}

var fileDescriptor_c47f403cbdc6a6e0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x62, 0x0b, 0x9d, 0x4a, 0x0f, 0x8b, 0x94, 0xd0, 0x53, 0x89, 0x1e, 0x2a, 0xc2,
	0x06, 0xea, 0x9f, 0xd0, 0x4b, 0x0e, 0x2b, 0x78, 0x53, 0xd8, 0x24, 0xb3, 0x10, 0x4a, 0x33, 0x71,
	0x67, 0xd3, 0xa2, 0xbf, 0x5e, 0x76, 0x37, 0x60, 0x05, 0xf1, 0x34, 0xf3, 0x76, 0x1e, 0xdf, 0xce,
	0x3c, 0xb8, 0x67, 0x6d, 0xd0, 0x7d, 0x96, 0x27, 0xb4, 0x9d, 0xe9, 0x1a, 0xed, 0x3a, 0xea, 0xcb,
	0xa1, 0xfe, 0xa5, 0xe5, 0x60, 0xc9, 0x91, 0x58, 0x1b, 0x96, 0xd1, 0x2d, 0x2f, 0xa7, 0x9b, 0x87,
	0x2f, 0x3e, 0x0c, 0xda, 0x1e, 0xd0, 0xca, 0x86, 0x8e, 0xa5, 0xa1, 0xb1, 0x6f, 0x23, 0xa7, 0xd6,
	0x8c, 0x1e, 0xe6, 0x6b, 0x84, 0x14, 0x4f, 0x00, 0x15, 0x9e, 0x15, 0x7e, 0x8c, 0xc8, 0x4e, 0x08,
	0xb8, 0x32, 0x63, 0xdf, 0xe4, 0xc9, 0x36, 0xd9, 0x2d, 0x54, 0xe8, 0xc5, 0x1a, 0xe6, 0xbe, 0x3e,
	0xb7, 0x79, 0xba, 0x4d, 0x76, 0x99, 0x9a, 0x94, 0x58, 0x41, 0xea, 0x28, 0xcf, 0x82, 0x33, 0x75,
	0x54, 0xbc, 0xc1, 0x32, 0x90, 0x78, 0xa0, 0x9e, 0x51, 0xdc, 0xc1, 0x8c, 0x9d, 0x76, 0x18, 0x58,
	0xcb, 0xfd, 0x4a, 0x1a, 0x96, 0xe1, 0xdf, 0x17, 0xff, 0xaa, 0xe2, 0x50, 0xdc, 0xc0, 0xec, 0x84,
	0x76, 0x62, 0x2f, 0x54, 0x14, 0x7e, 0x8d, 0x23, 0xb5, 0x38, 0xc1, 0x43, 0xbf, 0x7f, 0x87, 0xeb,
	0xd7, 0x8b, 0x2b, 0x45, 0x05, 0x59, 0x85, 0x67, 0x51, 0xc8, 0xbf, 0x53, 0x90, 0x3f, 0x57, 0x6d,
	0x6e, 0xff, 0xf5, 0xc4, 0x7d, 0xeb, 0x79, 0xc8, 0xe3, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x06,
	0x96, 0xdc, 0x4b, 0x81, 0x01, 0x00, 0x00,
}
