// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/email/pb/email.proto

package fs_base_email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

// EmailServer is the server API for Email service.
type EmailServer interface {
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base/email/pb/email.proto",
}

func init() { proto.RegisterFile("base/email/pb/email.proto", fileDescriptor_b1ac0040cc8418fa) }

var fileDescriptor_b1ac0040cc8418fa = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x4a, 0x2c, 0x4e,
	0xd5, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0xd1, 0x2f, 0x48, 0x82, 0x30, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x78, 0xd3, 0x8a, 0xf5, 0x40, 0xb2, 0x7a, 0x60, 0x41, 0x23, 0x76, 0x2e, 0x56, 0x57,
	0x10, 0x23, 0x89, 0x0d, 0x2c, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x0e, 0xd7, 0x52,
	0x3b, 0x00, 0x00, 0x00,
}
