// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/usersync/pb/usersync.proto

package fs_base_usersync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "zskparker.com/foundation/base/pb"
	pb1 "zskparker.com/foundation/base/userinfo/pb"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSyncHookRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSyncHookRequest) Reset()         { *m = GetSyncHookRequest{} }
func (m *GetSyncHookRequest) String() string { return proto.CompactTextString(m) }
func (*GetSyncHookRequest) ProtoMessage()    {}
func (*GetSyncHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{0}
}

func (m *GetSyncHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncHookRequest.Unmarshal(m, b)
}
func (m *GetSyncHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncHookRequest.Marshal(b, m, deterministic)
}
func (m *GetSyncHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncHookRequest.Merge(m, src)
}
func (m *GetSyncHookRequest) XXX_Size() int {
	return xxx_messageInfo_GetSyncHookRequest.Size(m)
}
func (m *GetSyncHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncHookRequest proto.InternalMessageInfo

func (m *GetSyncHookRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetSyncHookResponse struct {
	State                *pb.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSyncHookResponse) Reset()         { *m = GetSyncHookResponse{} }
func (m *GetSyncHookResponse) String() string { return proto.CompactTextString(m) }
func (*GetSyncHookResponse) ProtoMessage()    {}
func (*GetSyncHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{1}
}

func (m *GetSyncHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncHookResponse.Unmarshal(m, b)
}
func (m *GetSyncHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncHookResponse.Marshal(b, m, deterministic)
}
func (m *GetSyncHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncHookResponse.Merge(m, src)
}
func (m *GetSyncHookResponse) XXX_Size() int {
	return xxx_messageInfo_GetSyncHookResponse.Size(m)
}
func (m *GetSyncHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncHookResponse proto.InternalMessageInfo

func (m *GetSyncHookResponse) GetState() *pb.State {
	if m != nil {
		return m.State
	}
	return nil
}

type SyncUserRequest struct {
	Info                 *pb1.UserBaseInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncUserRequest) Reset()         { *m = SyncUserRequest{} }
func (m *SyncUserRequest) String() string { return proto.CompactTextString(m) }
func (*SyncUserRequest) ProtoMessage()    {}
func (*SyncUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{2}
}

func (m *SyncUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncUserRequest.Unmarshal(m, b)
}
func (m *SyncUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncUserRequest.Marshal(b, m, deterministic)
}
func (m *SyncUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncUserRequest.Merge(m, src)
}
func (m *SyncUserRequest) XXX_Size() int {
	return xxx_messageInfo_SyncUserRequest.Size(m)
}
func (m *SyncUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncUserRequest proto.InternalMessageInfo

func (m *SyncUserRequest) GetInfo() *pb1.UserBaseInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type AddProjectSyncHookRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Hook                 string   `protobuf:"bytes,3,opt,name=hook,proto3" json:"hook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectSyncHookRequest) Reset()         { *m = AddProjectSyncHookRequest{} }
func (m *AddProjectSyncHookRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectSyncHookRequest) ProtoMessage()    {}
func (*AddProjectSyncHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{3}
}

func (m *AddProjectSyncHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectSyncHookRequest.Unmarshal(m, b)
}
func (m *AddProjectSyncHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectSyncHookRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectSyncHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectSyncHookRequest.Merge(m, src)
}
func (m *AddProjectSyncHookRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectSyncHookRequest.Size(m)
}
func (m *AddProjectSyncHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectSyncHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectSyncHookRequest proto.InternalMessageInfo

func (m *AddProjectSyncHookRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AddProjectSyncHookRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AddProjectSyncHookRequest) GetHook() string {
	if m != nil {
		return m.Hook
	}
	return ""
}

type RemoveProjectSyncHookRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveProjectSyncHookRequest) Reset()         { *m = RemoveProjectSyncHookRequest{} }
func (m *RemoveProjectSyncHookRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveProjectSyncHookRequest) ProtoMessage()    {}
func (*RemoveProjectSyncHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{4}
}

func (m *RemoveProjectSyncHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveProjectSyncHookRequest.Unmarshal(m, b)
}
func (m *RemoveProjectSyncHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveProjectSyncHookRequest.Marshal(b, m, deterministic)
}
func (m *RemoveProjectSyncHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveProjectSyncHookRequest.Merge(m, src)
}
func (m *RemoveProjectSyncHookRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveProjectSyncHookRequest.Size(m)
}
func (m *RemoveProjectSyncHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveProjectSyncHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveProjectSyncHookRequest proto.InternalMessageInfo

func (m *RemoveProjectSyncHookRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RemoveProjectSyncHookRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type ModifyProjectSyncHookRequest struct {
	Meta                 *pb.Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Hook                 string   `protobuf:"bytes,3,opt,name=hook,proto3" json:"hook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyProjectSyncHookRequest) Reset()         { *m = ModifyProjectSyncHookRequest{} }
func (m *ModifyProjectSyncHookRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyProjectSyncHookRequest) ProtoMessage()    {}
func (*ModifyProjectSyncHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa1c5fc83c646957, []int{5}
}

func (m *ModifyProjectSyncHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyProjectSyncHookRequest.Unmarshal(m, b)
}
func (m *ModifyProjectSyncHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyProjectSyncHookRequest.Marshal(b, m, deterministic)
}
func (m *ModifyProjectSyncHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyProjectSyncHookRequest.Merge(m, src)
}
func (m *ModifyProjectSyncHookRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyProjectSyncHookRequest.Size(m)
}
func (m *ModifyProjectSyncHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyProjectSyncHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyProjectSyncHookRequest proto.InternalMessageInfo

func (m *ModifyProjectSyncHookRequest) GetMeta() *pb.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ModifyProjectSyncHookRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ModifyProjectSyncHookRequest) GetHook() string {
	if m != nil {
		return m.Hook
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSyncHookRequest)(nil), "fs.base.usersync.GetSyncHookRequest")
	proto.RegisterType((*GetSyncHookResponse)(nil), "fs.base.usersync.GetSyncHookResponse")
	proto.RegisterType((*SyncUserRequest)(nil), "fs.base.usersync.SyncUserRequest")
	proto.RegisterType((*AddProjectSyncHookRequest)(nil), "fs.base.usersync.AddProjectSyncHookRequest")
	proto.RegisterType((*RemoveProjectSyncHookRequest)(nil), "fs.base.usersync.RemoveProjectSyncHookRequest")
	proto.RegisterType((*ModifyProjectSyncHookRequest)(nil), "fs.base.usersync.ModifyProjectSyncHookRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSyncClient is the client API for UserSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSyncClient interface {
	// 添加项目同步钩子
	AddProjectSyncHook(ctx context.Context, in *AddProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 移除项目同步钩子
	RemoveProjectSyncHook(ctx context.Context, in *RemoveProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 修改项目同步钩子
	ModifyProjectSyncHook(ctx context.Context, in *ModifyProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error)
	// 获取同步钩子
	GetSyncHook(ctx context.Context, in *GetSyncHookRequest, opts ...grpc.CallOption) (*GetSyncHookResponse, error)
	// 同步用户信息到各个项目注册的同步钩子
	SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*pb.Response, error)
}

type userSyncClient struct {
	cc *grpc.ClientConn
}

func NewUserSyncClient(cc *grpc.ClientConn) UserSyncClient {
	return &userSyncClient{cc}
}

func (c *userSyncClient) AddProjectSyncHook(ctx context.Context, in *AddProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.usersync.UserSync/AddProjectSyncHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSyncClient) RemoveProjectSyncHook(ctx context.Context, in *RemoveProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.usersync.UserSync/RemoveProjectSyncHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSyncClient) ModifyProjectSyncHook(ctx context.Context, in *ModifyProjectSyncHookRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.usersync.UserSync/ModifyProjectSyncHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSyncClient) GetSyncHook(ctx context.Context, in *GetSyncHookRequest, opts ...grpc.CallOption) (*GetSyncHookResponse, error) {
	out := new(GetSyncHookResponse)
	err := c.cc.Invoke(ctx, "/fs.base.usersync.UserSync/GetSyncHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSyncClient) SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*pb.Response, error) {
	out := new(pb.Response)
	err := c.cc.Invoke(ctx, "/fs.base.usersync.UserSync/SyncUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSyncServer is the server API for UserSync service.
type UserSyncServer interface {
	// 添加项目同步钩子
	AddProjectSyncHook(context.Context, *AddProjectSyncHookRequest) (*pb.Response, error)
	// 移除项目同步钩子
	RemoveProjectSyncHook(context.Context, *RemoveProjectSyncHookRequest) (*pb.Response, error)
	// 修改项目同步钩子
	ModifyProjectSyncHook(context.Context, *ModifyProjectSyncHookRequest) (*pb.Response, error)
	// 获取同步钩子
	GetSyncHook(context.Context, *GetSyncHookRequest) (*GetSyncHookResponse, error)
	// 同步用户信息到各个项目注册的同步钩子
	SyncUser(context.Context, *SyncUserRequest) (*pb.Response, error)
}

func RegisterUserSyncServer(s *grpc.Server, srv UserSyncServer) {
	s.RegisterService(&_UserSync_serviceDesc, srv)
}

func _UserSync_AddProjectSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectSyncHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSyncServer).AddProjectSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.usersync.UserSync/AddProjectSyncHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSyncServer).AddProjectSyncHook(ctx, req.(*AddProjectSyncHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSync_RemoveProjectSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProjectSyncHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSyncServer).RemoveProjectSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.usersync.UserSync/RemoveProjectSyncHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSyncServer).RemoveProjectSyncHook(ctx, req.(*RemoveProjectSyncHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSync_ModifyProjectSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyProjectSyncHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSyncServer).ModifyProjectSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.usersync.UserSync/ModifyProjectSyncHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSyncServer).ModifyProjectSyncHook(ctx, req.(*ModifyProjectSyncHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSync_GetSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSyncServer).GetSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.usersync.UserSync/GetSyncHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSyncServer).GetSyncHook(ctx, req.(*GetSyncHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSync_SyncUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSyncServer).SyncUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fs.base.usersync.UserSync/SyncUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSyncServer).SyncUser(ctx, req.(*SyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fs.base.usersync.UserSync",
	HandlerType: (*UserSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProjectSyncHook",
			Handler:    _UserSync_AddProjectSyncHook_Handler,
		},
		{
			MethodName: "RemoveProjectSyncHook",
			Handler:    _UserSync_RemoveProjectSyncHook_Handler,
		},
		{
			MethodName: "ModifyProjectSyncHook",
			Handler:    _UserSync_ModifyProjectSyncHook_Handler,
		},
		{
			MethodName: "GetSyncHook",
			Handler:    _UserSync_GetSyncHook_Handler,
		},
		{
			MethodName: "SyncUser",
			Handler:    _UserSync_SyncUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/usersync/pb/usersync.proto",
}

func init() { proto.RegisterFile("base/usersync/pb/usersync.proto", fileDescriptor_aa1c5fc83c646957) }

var fileDescriptor_aa1c5fc83c646957 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xdf, 0x4b, 0xe3, 0x40,
	0x10, 0xa6, 0xd7, 0xde, 0xd1, 0x4e, 0xb9, 0x5f, 0x7b, 0x1c, 0xf4, 0x42, 0x39, 0xdb, 0x50, 0xa1,
	0x50, 0xd8, 0x40, 0x7d, 0x50, 0xf0, 0x45, 0x05, 0xd1, 0x3e, 0x14, 0x24, 0xd5, 0x17, 0x5f, 0x24,
	0x3f, 0x26, 0x58, 0x43, 0x33, 0x31, 0xbb, 0x15, 0xea, 0x1f, 0xe6, 0xdf, 0x27, 0xbb, 0x69, 0x62,
	0x6d, 0xd2, 0x0a, 0x82, 0x3e, 0xed, 0x30, 0xf3, 0x7d, 0xdf, 0xcc, 0x7e, 0xcc, 0xc0, 0x8e, 0xeb,
	0x08, 0xb4, 0xe6, 0x02, 0x13, 0xb1, 0x88, 0x3c, 0x2b, 0x76, 0xf3, 0x98, 0xc7, 0x09, 0x49, 0x62,
	0xbf, 0x02, 0xc1, 0x15, 0x86, 0x67, 0x79, 0x63, 0xf0, 0x28, 0xc2, 0xd8, 0x49, 0x42, 0x4c, 0xb8,
	0x47, 0x33, 0x2b, 0xa0, 0x79, 0xe4, 0x3b, 0x72, 0x4a, 0x91, 0xa5, 0xb5, 0x62, 0x57, 0xbf, 0x29,
	0xdd, 0x38, 0xd8, 0x0e, 0x56, 0xa2, 0xd3, 0x28, 0xa0, 0xac, 0xb1, 0x8a, 0x53, 0xa6, 0xb9, 0x0f,
	0xec, 0x0c, 0xe5, 0x64, 0x11, 0x79, 0xe7, 0x44, 0xa1, 0x8d, 0xf7, 0x73, 0x14, 0x92, 0x75, 0xa1,
	0x36, 0x43, 0xe9, 0xb4, 0x2a, 0x9d, 0x4a, 0xbf, 0x39, 0xfc, 0xce, 0xb3, 0xe9, 0xc6, 0x28, 0x1d,
	0x5b, 0x97, 0xcc, 0x43, 0xf8, 0xf3, 0x8a, 0x28, 0x62, 0x8a, 0x04, 0xb2, 0x1e, 0x7c, 0x15, 0xd2,
	0x91, 0xb8, 0xa4, 0xfe, 0xc8, 0xa9, 0x13, 0x95, 0xb5, 0xd3, 0xa2, 0x79, 0x0a, 0x3f, 0x15, 0xf3,
	0x4a, 0x60, 0x92, 0xb5, 0x1c, 0x42, 0x4d, 0x8d, 0xb5, 0xe4, 0xfd, 0xe7, 0xab, 0x86, 0xe8, 0x79,
	0x15, 0xf8, 0xc4, 0x11, 0x38, 0x8a, 0x02, 0xb2, 0x35, 0xd6, 0x8c, 0xe1, 0xdf, 0xb1, 0xef, 0x5f,
	0x24, 0x74, 0x87, 0xde, 0x3b, 0xfe, 0xc0, 0xda, 0xd0, 0x88, 0x53, 0xf2, 0xc8, 0x6f, 0x7d, 0xe9,
	0x54, 0xfa, 0x0d, 0xfb, 0x25, 0xc1, 0x18, 0xd4, 0x6e, 0x89, 0xc2, 0x56, 0x55, 0x17, 0x74, 0x6c,
	0xde, 0x40, 0xdb, 0xc6, 0x19, 0x3d, 0xe0, 0x07, 0x35, 0x35, 0x05, 0xb4, 0xc7, 0xe4, 0x4f, 0x83,
	0xc5, 0x27, 0xfe, 0x6a, 0xf8, 0x54, 0x85, 0xba, 0xb2, 0x57, 0x35, 0x63, 0x97, 0xc0, 0x8a, 0xa6,
	0xb2, 0x01, 0x5f, 0xdf, 0x50, 0xbe, 0xd1, 0x7a, 0xe3, 0x77, 0x0e, 0xce, 0xf7, 0xe2, 0x1a, 0xfe,
	0x96, 0x1a, 0xc7, 0x78, 0x51, 0x78, 0x9b, 0xc3, 0x1b, 0xb4, 0x4b, 0x3d, 0x2b, 0xd3, 0xde, 0x66,
	0x6e, 0xb9, 0x76, 0x73, 0x65, 0xcd, 0x59, 0xaf, 0xa8, 0x58, 0x3c, 0x1f, 0x63, 0xf7, 0x0d, 0xd4,
	0x52, 0xfb, 0x08, 0xea, 0xd9, 0x15, 0xb0, 0x6e, 0x91, 0xb2, 0x76, 0x21, 0x25, 0xd3, 0xb9, 0xdf,
	0xf4, 0x11, 0xef, 0x3d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x92, 0x6c, 0x3e, 0x61, 0x60, 0x04, 0x00,
	0x00,
}
